// <auto-generated />
using System;
using DormitoryManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DormitoryManagement.Migrations
{
    [DbContext(typeof(DormitoryContext))]
    [Migration("20231026204126_AddingRoomSetup")]
    partial class AddingRoomSetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-rc.1.23419.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DormitoryManagement.Data.Models.Building", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Buildings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("58c02d2e-8483-45fc-b0c3-5689642790bd"),
                            Name = "Building A"
                        },
                        new
                        {
                            Id = new Guid("e3ab161e-9020-433a-8cc9-096a42e16702"),
                            Name = "Building B"
                        });
                });

            modelBuilder.Entity("DormitoryManagement.Data.Models.Floor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uuid");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("Floors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7c20b0b1-019d-4727-8483-130e5a802882"),
                            BuildingId = new Guid("58c02d2e-8483-45fc-b0c3-5689642790bd"),
                            Number = 1
                        },
                        new
                        {
                            Id = new Guid("2e3b8264-4ac0-4ea1-bc58-dc3437db31d5"),
                            BuildingId = new Guid("58c02d2e-8483-45fc-b0c3-5689642790bd"),
                            Number = 2
                        },
                        new
                        {
                            Id = new Guid("0801c872-16b3-4202-9f32-36c287fce094"),
                            BuildingId = new Guid("e3ab161e-9020-433a-8cc9-096a42e16702"),
                            Number = 1
                        },
                        new
                        {
                            Id = new Guid("ce898d7d-c8d8-4aed-a604-8e49b022f766"),
                            BuildingId = new Guid("e3ab161e-9020-433a-8cc9-096a42e16702"),
                            Number = 2
                        });
                });

            modelBuilder.Entity("DormitoryManagement.Data.Models.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FloorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FloorId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("39efbe04-0b4b-4c2a-a6a5-81aeb4d5da86"),
                            FloorId = new Guid("7c20b0b1-019d-4727-8483-130e5a802882"),
                            Number = "101"
                        },
                        new
                        {
                            Id = new Guid("4a2abfd8-e20d-4da6-84b0-8234f6fcae85"),
                            FloorId = new Guid("7c20b0b1-019d-4727-8483-130e5a802882"),
                            Number = "102"
                        },
                        new
                        {
                            Id = new Guid("20f2b16f-078d-43a0-8000-7b1ac89708c5"),
                            FloorId = new Guid("7c20b0b1-019d-4727-8483-130e5a802882"),
                            Number = "103"
                        },
                        new
                        {
                            Id = new Guid("edf8f8cb-4ef3-4ed6-8bc1-4831dcca975c"),
                            FloorId = new Guid("2e3b8264-4ac0-4ea1-bc58-dc3437db31d5"),
                            Number = "201"
                        },
                        new
                        {
                            Id = new Guid("b6d1c8d8-08ea-4c3e-96a0-6835c828966f"),
                            FloorId = new Guid("2e3b8264-4ac0-4ea1-bc58-dc3437db31d5"),
                            Number = "202"
                        },
                        new
                        {
                            Id = new Guid("23b34d21-ecb5-4408-8d57-a567d8e0fec2"),
                            FloorId = new Guid("2e3b8264-4ac0-4ea1-bc58-dc3437db31d5"),
                            Number = "203"
                        },
                        new
                        {
                            Id = new Guid("7e1e65c5-011c-47d1-8aa6-9eb7813abe9f"),
                            FloorId = new Guid("2e3b8264-4ac0-4ea1-bc58-dc3437db31d5"),
                            Number = "204"
                        },
                        new
                        {
                            Id = new Guid("b92c968f-e11a-4888-9f61-2a1668bc3642"),
                            FloorId = new Guid("0801c872-16b3-4202-9f32-36c287fce094"),
                            Number = "301"
                        },
                        new
                        {
                            Id = new Guid("1a81f689-92d3-4813-bbce-645e9b360377"),
                            FloorId = new Guid("0801c872-16b3-4202-9f32-36c287fce094"),
                            Number = "302"
                        },
                        new
                        {
                            Id = new Guid("24788378-6e5e-40a0-8a22-c901d4052a89"),
                            FloorId = new Guid("0801c872-16b3-4202-9f32-36c287fce094"),
                            Number = "303"
                        },
                        new
                        {
                            Id = new Guid("cb97ba0d-03a9-413f-8197-8154e7cf603c"),
                            FloorId = new Guid("0801c872-16b3-4202-9f32-36c287fce094"),
                            Number = "304"
                        },
                        new
                        {
                            Id = new Guid("99d3beec-1ff4-47bd-8a9a-ac20c48f6b78"),
                            FloorId = new Guid("ce898d7d-c8d8-4aed-a604-8e49b022f766"),
                            Number = "401"
                        },
                        new
                        {
                            Id = new Guid("749410a0-c185-4df3-8469-ef28e8552feb"),
                            FloorId = new Guid("ce898d7d-c8d8-4aed-a604-8e49b022f766"),
                            Number = "402"
                        },
                        new
                        {
                            Id = new Guid("54266368-6b58-4a54-88b0-1fc368974d2f"),
                            FloorId = new Guid("ce898d7d-c8d8-4aed-a604-8e49b022f766"),
                            Number = "403"
                        });
                });

            modelBuilder.Entity("DormitoryManagement.Data.Models.Floor", b =>
                {
                    b.HasOne("DormitoryManagement.Data.Models.Building", "Building")
                        .WithMany("Floors")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("DormitoryManagement.Data.Models.Room", b =>
                {
                    b.HasOne("DormitoryManagement.Data.Models.Floor", "Floor")
                        .WithMany("Rooms")
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Floor");
                });

            modelBuilder.Entity("DormitoryManagement.Data.Models.Building", b =>
                {
                    b.Navigation("Floors");
                });

            modelBuilder.Entity("DormitoryManagement.Data.Models.Floor", b =>
                {
                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
