// <auto-generated />
using System;
using DormitoryManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DormitoryManagement.Migrations
{
    [DbContext(typeof(DormitoryContext))]
    [Migration("20231105091420_AddRoomSetup")]
    partial class AddRoomSetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-rc.2.23480.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DormitoryManagement.Data.Models.Building", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Buildings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9365f827-8055-41f0-8e7e-a32891b46d2e"),
                            Name = "Building A"
                        },
                        new
                        {
                            Id = new Guid("32a28f1c-7d20-47e4-997d-f4c3bb974e23"),
                            Name = "Building B"
                        });
                });

            modelBuilder.Entity("DormitoryManagement.Data.Models.Floor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uuid");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("Floors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1867af08-63c7-4517-bfbe-0c99c67318cf"),
                            BuildingId = new Guid("9365f827-8055-41f0-8e7e-a32891b46d2e"),
                            Number = 1
                        },
                        new
                        {
                            Id = new Guid("70b54e27-bde1-468c-930a-f638c25f22df"),
                            BuildingId = new Guid("9365f827-8055-41f0-8e7e-a32891b46d2e"),
                            Number = 2
                        },
                        new
                        {
                            Id = new Guid("75234197-e4a8-407e-85e8-80279350db7f"),
                            BuildingId = new Guid("32a28f1c-7d20-47e4-997d-f4c3bb974e23"),
                            Number = 1
                        },
                        new
                        {
                            Id = new Guid("981a6210-5098-4cc1-9917-c42f777cfe9a"),
                            BuildingId = new Guid("32a28f1c-7d20-47e4-997d-f4c3bb974e23"),
                            Number = 2
                        });
                });

            modelBuilder.Entity("DormitoryManagement.Data.Models.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FloorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FloorId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f0be2115-a305-4d1c-87ce-a35f547b68aa"),
                            FloorId = new Guid("1867af08-63c7-4517-bfbe-0c99c67318cf"),
                            Number = "101"
                        },
                        new
                        {
                            Id = new Guid("427c1c4a-5313-427a-97dc-110c965b0eab"),
                            FloorId = new Guid("1867af08-63c7-4517-bfbe-0c99c67318cf"),
                            Number = "102"
                        },
                        new
                        {
                            Id = new Guid("3093a6d7-ddae-456c-9809-8acdbb405d7a"),
                            FloorId = new Guid("1867af08-63c7-4517-bfbe-0c99c67318cf"),
                            Number = "103"
                        },
                        new
                        {
                            Id = new Guid("bb042b20-533f-44d2-b070-7aa05fc3ddb5"),
                            FloorId = new Guid("70b54e27-bde1-468c-930a-f638c25f22df"),
                            Number = "201"
                        },
                        new
                        {
                            Id = new Guid("8dea9c3a-672a-462a-bcc7-96fa2df682c0"),
                            FloorId = new Guid("70b54e27-bde1-468c-930a-f638c25f22df"),
                            Number = "202"
                        },
                        new
                        {
                            Id = new Guid("40601319-87b8-4100-8814-d61466ea0985"),
                            FloorId = new Guid("70b54e27-bde1-468c-930a-f638c25f22df"),
                            Number = "203"
                        },
                        new
                        {
                            Id = new Guid("c2c0560e-62f1-436e-8886-453d7bc4a359"),
                            FloorId = new Guid("70b54e27-bde1-468c-930a-f638c25f22df"),
                            Number = "204"
                        },
                        new
                        {
                            Id = new Guid("b8652abf-a18c-4105-be6e-8c249c68181e"),
                            FloorId = new Guid("75234197-e4a8-407e-85e8-80279350db7f"),
                            Number = "301"
                        },
                        new
                        {
                            Id = new Guid("aae92210-397b-4185-80c9-234e36d77089"),
                            FloorId = new Guid("75234197-e4a8-407e-85e8-80279350db7f"),
                            Number = "302"
                        },
                        new
                        {
                            Id = new Guid("c96dcd55-d7b2-4a56-90dc-11dc3c334a0e"),
                            FloorId = new Guid("75234197-e4a8-407e-85e8-80279350db7f"),
                            Number = "303"
                        },
                        new
                        {
                            Id = new Guid("11de0c6b-312e-4998-beb8-3ef73008902a"),
                            FloorId = new Guid("75234197-e4a8-407e-85e8-80279350db7f"),
                            Number = "304"
                        },
                        new
                        {
                            Id = new Guid("bb067df4-3b41-4637-9ce6-062e1bba9e19"),
                            FloorId = new Guid("981a6210-5098-4cc1-9917-c42f777cfe9a"),
                            Number = "401"
                        },
                        new
                        {
                            Id = new Guid("f6484657-34de-44c2-804b-737bfa0f67e2"),
                            FloorId = new Guid("981a6210-5098-4cc1-9917-c42f777cfe9a"),
                            Number = "402"
                        },
                        new
                        {
                            Id = new Guid("f08da799-7452-412f-b8e4-9aef82ce8444"),
                            FloorId = new Guid("981a6210-5098-4cc1-9917-c42f777cfe9a"),
                            Number = "403"
                        });
                });

            modelBuilder.Entity("DormitoryManagement.Data.Models.Floor", b =>
                {
                    b.HasOne("DormitoryManagement.Data.Models.Building", "Building")
                        .WithMany("Floors")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("DormitoryManagement.Data.Models.Room", b =>
                {
                    b.HasOne("DormitoryManagement.Data.Models.Floor", "Floor")
                        .WithMany("Rooms")
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Floor");
                });

            modelBuilder.Entity("DormitoryManagement.Data.Models.Building", b =>
                {
                    b.Navigation("Floors");
                });

            modelBuilder.Entity("DormitoryManagement.Data.Models.Floor", b =>
                {
                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
