// <auto-generated />
using System;
using DormitoryManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DormitoryManagement.Migrations
{
    [DbContext(typeof(DormitoryContext))]
    [Migration("20240103095720_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DormitoryManagement.Data.Models.Building", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Buildings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("55d39593-b0da-4387-a0c9-bb2fe455efec"),
                            Name = "Building A"
                        },
                        new
                        {
                            Id = new Guid("dcf76e4f-d322-44c0-bb5b-ceb43ab333dd"),
                            Name = "Building B"
                        });
                });

            modelBuilder.Entity("DormitoryManagement.Data.Models.Floor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uuid");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("Floors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2fdc137e-b97f-4679-b96b-1fda9e269e99"),
                            BuildingId = new Guid("55d39593-b0da-4387-a0c9-bb2fe455efec"),
                            Number = 1
                        },
                        new
                        {
                            Id = new Guid("bf782ef9-b684-4d86-bd26-e8ed93e93971"),
                            BuildingId = new Guid("55d39593-b0da-4387-a0c9-bb2fe455efec"),
                            Number = 2
                        },
                        new
                        {
                            Id = new Guid("1e629824-4318-4c1d-ac46-a4b616e97ccd"),
                            BuildingId = new Guid("dcf76e4f-d322-44c0-bb5b-ceb43ab333dd"),
                            Number = 1
                        },
                        new
                        {
                            Id = new Guid("e1585c2a-02e5-44c7-b86a-ee43e173593e"),
                            BuildingId = new Guid("dcf76e4f-d322-44c0-bb5b-ceb43ab333dd"),
                            Number = 2
                        });
                });

            modelBuilder.Entity("DormitoryManagement.Data.Models.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("InventoryItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("436f3b3b-171c-49c9-996a-dd3b29cea176"),
                            Name = "Chair"
                        },
                        new
                        {
                            Id = new Guid("38792418-a30d-483c-843c-3a072addabbc"),
                            Name = "Desk"
                        },
                        new
                        {
                            Id = new Guid("6a9a0f85-fac2-4904-919e-be0d68e0e50a"),
                            Name = "Bed"
                        },
                        new
                        {
                            Id = new Guid("3fa8ac09-db05-4ef5-b341-e003d132dc58"),
                            Name = "Lamp"
                        },
                        new
                        {
                            Id = new Guid("accf4824-a50e-4122-9777-a826c75288f4"),
                            Name = "Bookshelf"
                        },
                        new
                        {
                            Id = new Guid("1d1b397c-0d07-4398-aca7-5c7ea4d2ca12"),
                            Name = "Wardrobe"
                        },
                        new
                        {
                            Id = new Guid("c526cd14-b087-4a47-b311-810d99134cd2"),
                            Name = "Curtains"
                        });
                });

            modelBuilder.Entity("DormitoryManagement.Data.Models.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AllowedPersons")
                        .HasColumnType("integer");

                    b.Property<Guid>("FloorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FloorId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33e79c0e-5fb2-47a6-9599-e8c0c484c338"),
                            AllowedPersons = 4,
                            FloorId = new Guid("2fdc137e-b97f-4679-b96b-1fda9e269e99"),
                            Number = "A1-01"
                        },
                        new
                        {
                            Id = new Guid("f8e81dcb-ed4a-4456-91a8-5c0e922dff41"),
                            AllowedPersons = 4,
                            FloorId = new Guid("2fdc137e-b97f-4679-b96b-1fda9e269e99"),
                            Number = "A1-02"
                        },
                        new
                        {
                            Id = new Guid("740f9a7a-5fb3-4731-89ac-3a3263b11299"),
                            AllowedPersons = 5,
                            FloorId = new Guid("2fdc137e-b97f-4679-b96b-1fda9e269e99"),
                            Number = "A1-03"
                        },
                        new
                        {
                            Id = new Guid("5fb6d4e2-5c3a-4d2c-84b4-61324910820a"),
                            AllowedPersons = 5,
                            FloorId = new Guid("2fdc137e-b97f-4679-b96b-1fda9e269e99"),
                            Number = "A1-04"
                        },
                        new
                        {
                            Id = new Guid("664efd94-8791-47e0-93f5-a90471a719ce"),
                            AllowedPersons = 4,
                            FloorId = new Guid("2fdc137e-b97f-4679-b96b-1fda9e269e99"),
                            Number = "A1-05"
                        },
                        new
                        {
                            Id = new Guid("b64f485b-7269-428f-86b6-18644500d0c8"),
                            AllowedPersons = 5,
                            FloorId = new Guid("2fdc137e-b97f-4679-b96b-1fda9e269e99"),
                            Number = "A1-06"
                        },
                        new
                        {
                            Id = new Guid("1263221d-1089-46de-8072-5a7841fb7ef2"),
                            AllowedPersons = 4,
                            FloorId = new Guid("2fdc137e-b97f-4679-b96b-1fda9e269e99"),
                            Number = "A1-07"
                        },
                        new
                        {
                            Id = new Guid("0d9da574-4fd0-4392-9432-809db6df05f0"),
                            AllowedPersons = 5,
                            FloorId = new Guid("2fdc137e-b97f-4679-b96b-1fda9e269e99"),
                            Number = "A1-08"
                        },
                        new
                        {
                            Id = new Guid("b379d037-36eb-4a43-a2ad-df02ddd6c0c6"),
                            AllowedPersons = 3,
                            FloorId = new Guid("2fdc137e-b97f-4679-b96b-1fda9e269e99"),
                            Number = "A1-09"
                        },
                        new
                        {
                            Id = new Guid("f233b8ba-f83e-4a93-900a-9011f74bf290"),
                            AllowedPersons = 3,
                            FloorId = new Guid("2fdc137e-b97f-4679-b96b-1fda9e269e99"),
                            Number = "A1-10"
                        },
                        new
                        {
                            Id = new Guid("ea378932-757c-46eb-a9b7-074379b6c130"),
                            AllowedPersons = 4,
                            FloorId = new Guid("bf782ef9-b684-4d86-bd26-e8ed93e93971"),
                            Number = "A2-01"
                        },
                        new
                        {
                            Id = new Guid("293f5ab3-f6a3-4456-9f07-0f4d4d879b17"),
                            AllowedPersons = 4,
                            FloorId = new Guid("bf782ef9-b684-4d86-bd26-e8ed93e93971"),
                            Number = "A2-02"
                        },
                        new
                        {
                            Id = new Guid("0f0c2db7-0760-4b68-a7ea-92ab8f02087b"),
                            AllowedPersons = 4,
                            FloorId = new Guid("bf782ef9-b684-4d86-bd26-e8ed93e93971"),
                            Number = "A2-03"
                        },
                        new
                        {
                            Id = new Guid("79551927-0e12-4f75-9806-98d4f76ccc2f"),
                            AllowedPersons = 3,
                            FloorId = new Guid("bf782ef9-b684-4d86-bd26-e8ed93e93971"),
                            Number = "A2-04"
                        },
                        new
                        {
                            Id = new Guid("8db3a69a-e938-400a-b99b-1be55722a816"),
                            AllowedPersons = 3,
                            FloorId = new Guid("bf782ef9-b684-4d86-bd26-e8ed93e93971"),
                            Number = "A2-05"
                        },
                        new
                        {
                            Id = new Guid("1fb6e404-0af3-41a6-98c9-f97a8765d299"),
                            AllowedPersons = 5,
                            FloorId = new Guid("bf782ef9-b684-4d86-bd26-e8ed93e93971"),
                            Number = "A2-06"
                        },
                        new
                        {
                            Id = new Guid("b9003860-62dd-42f5-b510-760d3e715ac2"),
                            AllowedPersons = 3,
                            FloorId = new Guid("bf782ef9-b684-4d86-bd26-e8ed93e93971"),
                            Number = "A2-07"
                        },
                        new
                        {
                            Id = new Guid("cb30ad96-44a2-4f05-9134-e891eb55177f"),
                            AllowedPersons = 3,
                            FloorId = new Guid("bf782ef9-b684-4d86-bd26-e8ed93e93971"),
                            Number = "A2-08"
                        },
                        new
                        {
                            Id = new Guid("a41f1d35-7849-47d8-9122-feebed9f0af2"),
                            AllowedPersons = 3,
                            FloorId = new Guid("bf782ef9-b684-4d86-bd26-e8ed93e93971"),
                            Number = "A2-09"
                        },
                        new
                        {
                            Id = new Guid("60104d45-1f95-47f7-ad6c-abbcfa3c5c5f"),
                            AllowedPersons = 4,
                            FloorId = new Guid("bf782ef9-b684-4d86-bd26-e8ed93e93971"),
                            Number = "A2-10"
                        },
                        new
                        {
                            Id = new Guid("0174d0fd-fba9-46bf-8eb3-c5152d0eaa38"),
                            AllowedPersons = 5,
                            FloorId = new Guid("1e629824-4318-4c1d-ac46-a4b616e97ccd"),
                            Number = "B1-01"
                        },
                        new
                        {
                            Id = new Guid("f5af0699-4280-4c91-a8d7-05873ed37854"),
                            AllowedPersons = 4,
                            FloorId = new Guid("1e629824-4318-4c1d-ac46-a4b616e97ccd"),
                            Number = "B1-02"
                        },
                        new
                        {
                            Id = new Guid("c46a33c4-5aa5-4d99-83e8-6d266d94fe51"),
                            AllowedPersons = 5,
                            FloorId = new Guid("1e629824-4318-4c1d-ac46-a4b616e97ccd"),
                            Number = "B1-03"
                        },
                        new
                        {
                            Id = new Guid("e62620f7-4612-4b62-98d5-bff192d83494"),
                            AllowedPersons = 5,
                            FloorId = new Guid("1e629824-4318-4c1d-ac46-a4b616e97ccd"),
                            Number = "B1-04"
                        },
                        new
                        {
                            Id = new Guid("43b1aadb-ced0-496a-b46a-f54732bf03eb"),
                            AllowedPersons = 4,
                            FloorId = new Guid("1e629824-4318-4c1d-ac46-a4b616e97ccd"),
                            Number = "B1-05"
                        },
                        new
                        {
                            Id = new Guid("f77269e4-005e-41bb-bb4f-6f0c3bc07c78"),
                            AllowedPersons = 3,
                            FloorId = new Guid("1e629824-4318-4c1d-ac46-a4b616e97ccd"),
                            Number = "B1-06"
                        },
                        new
                        {
                            Id = new Guid("63c3b25f-c73e-4738-8d85-1e945ae8cea3"),
                            AllowedPersons = 3,
                            FloorId = new Guid("1e629824-4318-4c1d-ac46-a4b616e97ccd"),
                            Number = "B1-07"
                        },
                        new
                        {
                            Id = new Guid("735de6ab-bfd8-40c5-abd1-7706600bf428"),
                            AllowedPersons = 3,
                            FloorId = new Guid("1e629824-4318-4c1d-ac46-a4b616e97ccd"),
                            Number = "B1-08"
                        },
                        new
                        {
                            Id = new Guid("92701ba7-6787-44b2-ab2b-364e75f85730"),
                            AllowedPersons = 3,
                            FloorId = new Guid("1e629824-4318-4c1d-ac46-a4b616e97ccd"),
                            Number = "B1-09"
                        },
                        new
                        {
                            Id = new Guid("4949b9c4-d8a1-4cf0-a875-5b52ae94ff91"),
                            AllowedPersons = 3,
                            FloorId = new Guid("1e629824-4318-4c1d-ac46-a4b616e97ccd"),
                            Number = "B1-10"
                        },
                        new
                        {
                            Id = new Guid("03e3c78c-343b-4836-bae3-207f9436ba17"),
                            AllowedPersons = 3,
                            FloorId = new Guid("e1585c2a-02e5-44c7-b86a-ee43e173593e"),
                            Number = "B2-01"
                        },
                        new
                        {
                            Id = new Guid("fddd9a83-f51d-4880-a4a0-79a97671b538"),
                            AllowedPersons = 4,
                            FloorId = new Guid("e1585c2a-02e5-44c7-b86a-ee43e173593e"),
                            Number = "B2-02"
                        },
                        new
                        {
                            Id = new Guid("1a024e28-3060-4d23-9c41-b5960c894f8f"),
                            AllowedPersons = 4,
                            FloorId = new Guid("e1585c2a-02e5-44c7-b86a-ee43e173593e"),
                            Number = "B2-03"
                        },
                        new
                        {
                            Id = new Guid("acf42373-049d-4b01-b60b-2ff4821f3991"),
                            AllowedPersons = 3,
                            FloorId = new Guid("e1585c2a-02e5-44c7-b86a-ee43e173593e"),
                            Number = "B2-04"
                        },
                        new
                        {
                            Id = new Guid("07fe95f1-306c-42bc-a497-0f4975e86099"),
                            AllowedPersons = 4,
                            FloorId = new Guid("e1585c2a-02e5-44c7-b86a-ee43e173593e"),
                            Number = "B2-05"
                        },
                        new
                        {
                            Id = new Guid("c625aac5-d374-4c68-a883-4ee886edb9e4"),
                            AllowedPersons = 3,
                            FloorId = new Guid("e1585c2a-02e5-44c7-b86a-ee43e173593e"),
                            Number = "B2-06"
                        },
                        new
                        {
                            Id = new Guid("aae4ce69-2f3d-4dd8-9380-b1acf986f565"),
                            AllowedPersons = 3,
                            FloorId = new Guid("e1585c2a-02e5-44c7-b86a-ee43e173593e"),
                            Number = "B2-07"
                        },
                        new
                        {
                            Id = new Guid("3f3773d4-5437-46dd-8705-ad5c0e7df8aa"),
                            AllowedPersons = 3,
                            FloorId = new Guid("e1585c2a-02e5-44c7-b86a-ee43e173593e"),
                            Number = "B2-08"
                        },
                        new
                        {
                            Id = new Guid("75c5cd05-a06a-40ec-80bb-0d370ccd7327"),
                            AllowedPersons = 4,
                            FloorId = new Guid("e1585c2a-02e5-44c7-b86a-ee43e173593e"),
                            Number = "B2-09"
                        },
                        new
                        {
                            Id = new Guid("08c722d2-f819-4ef8-9441-fafc536a158a"),
                            AllowedPersons = 5,
                            FloorId = new Guid("e1585c2a-02e5-44c7-b86a-ee43e173593e"),
                            Number = "B2-10"
                        });
                });

            modelBuilder.Entity("DormitoryManagement.Data.Models.RoomAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomAssignment");
                });

            modelBuilder.Entity("DormitoryManagement.Data.Models.RoomInventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActualQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("ExpectedQuantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("InventoryItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InventoryItemId");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomInventories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3d83b701-341f-46fb-94fd-79d9556b06c0"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("3fa8ac09-db05-4ef5-b341-e003d132dc58"),
                            RoomId = new Guid("33e79c0e-5fb2-47a6-9599-e8c0c484c338")
                        },
                        new
                        {
                            Id = new Guid("562e4b15-c4fd-4567-8376-f15c47363900"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("c526cd14-b087-4a47-b311-810d99134cd2"),
                            RoomId = new Guid("33e79c0e-5fb2-47a6-9599-e8c0c484c338")
                        },
                        new
                        {
                            Id = new Guid("8851d3bd-55e7-4e55-a532-02ff9884153f"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("accf4824-a50e-4122-9777-a826c75288f4"),
                            RoomId = new Guid("33e79c0e-5fb2-47a6-9599-e8c0c484c338")
                        },
                        new
                        {
                            Id = new Guid("c2fd2aeb-be88-47a0-b1a9-7036b28cdf66"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("436f3b3b-171c-49c9-996a-dd3b29cea176"),
                            RoomId = new Guid("33e79c0e-5fb2-47a6-9599-e8c0c484c338")
                        },
                        new
                        {
                            Id = new Guid("eb6187f4-4843-40c0-bbd1-8eda692b217d"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("3fa8ac09-db05-4ef5-b341-e003d132dc58"),
                            RoomId = new Guid("f8e81dcb-ed4a-4456-91a8-5c0e922dff41")
                        },
                        new
                        {
                            Id = new Guid("7ed0e6cb-d9d0-4f61-a875-b18d66a86e5a"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("38792418-a30d-483c-843c-3a072addabbc"),
                            RoomId = new Guid("f8e81dcb-ed4a-4456-91a8-5c0e922dff41")
                        },
                        new
                        {
                            Id = new Guid("20390396-6dfd-40f3-ba9b-0bad66a9e217"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("1d1b397c-0d07-4398-aca7-5c7ea4d2ca12"),
                            RoomId = new Guid("f8e81dcb-ed4a-4456-91a8-5c0e922dff41")
                        },
                        new
                        {
                            Id = new Guid("ed7cba61-5d7a-4513-9195-082e72afaf3b"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("6a9a0f85-fac2-4904-919e-be0d68e0e50a"),
                            RoomId = new Guid("f8e81dcb-ed4a-4456-91a8-5c0e922dff41")
                        },
                        new
                        {
                            Id = new Guid("a575eb48-ea53-4eee-893e-6fc1a61a4feb"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("436f3b3b-171c-49c9-996a-dd3b29cea176"),
                            RoomId = new Guid("f8e81dcb-ed4a-4456-91a8-5c0e922dff41")
                        },
                        new
                        {
                            Id = new Guid("1eaed6e5-091a-4a3e-98fe-e8e1e7291b1e"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("6a9a0f85-fac2-4904-919e-be0d68e0e50a"),
                            RoomId = new Guid("740f9a7a-5fb3-4731-89ac-3a3263b11299")
                        },
                        new
                        {
                            Id = new Guid("4010ea4f-f6f2-4379-b015-549d464054b1"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("436f3b3b-171c-49c9-996a-dd3b29cea176"),
                            RoomId = new Guid("740f9a7a-5fb3-4731-89ac-3a3263b11299")
                        },
                        new
                        {
                            Id = new Guid("8253f096-938f-48f9-a9b7-23150805329e"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("c526cd14-b087-4a47-b311-810d99134cd2"),
                            RoomId = new Guid("5fb6d4e2-5c3a-4d2c-84b4-61324910820a")
                        },
                        new
                        {
                            Id = new Guid("4c69c086-dada-4ec4-8cd7-fb4e5d208f2f"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("1d1b397c-0d07-4398-aca7-5c7ea4d2ca12"),
                            RoomId = new Guid("5fb6d4e2-5c3a-4d2c-84b4-61324910820a")
                        },
                        new
                        {
                            Id = new Guid("cc02dc16-4599-4ec3-9d08-0089c6b497c7"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("accf4824-a50e-4122-9777-a826c75288f4"),
                            RoomId = new Guid("5fb6d4e2-5c3a-4d2c-84b4-61324910820a")
                        },
                        new
                        {
                            Id = new Guid("b38479d7-2dc8-40ae-9d65-adbf2bc29c74"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("3fa8ac09-db05-4ef5-b341-e003d132dc58"),
                            RoomId = new Guid("5fb6d4e2-5c3a-4d2c-84b4-61324910820a")
                        },
                        new
                        {
                            Id = new Guid("afb3a7f7-ca11-41b7-bdae-872ce3a4fe19"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("c526cd14-b087-4a47-b311-810d99134cd2"),
                            RoomId = new Guid("664efd94-8791-47e0-93f5-a90471a719ce")
                        },
                        new
                        {
                            Id = new Guid("bcb4e97e-0b3d-41b1-b565-828932ec4fad"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("accf4824-a50e-4122-9777-a826c75288f4"),
                            RoomId = new Guid("664efd94-8791-47e0-93f5-a90471a719ce")
                        },
                        new
                        {
                            Id = new Guid("42e89444-fbca-4671-9633-a7c9cb1a1fc5"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("6a9a0f85-fac2-4904-919e-be0d68e0e50a"),
                            RoomId = new Guid("664efd94-8791-47e0-93f5-a90471a719ce")
                        },
                        new
                        {
                            Id = new Guid("ddc74259-df26-462f-b964-a6de5e858f53"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("38792418-a30d-483c-843c-3a072addabbc"),
                            RoomId = new Guid("664efd94-8791-47e0-93f5-a90471a719ce")
                        },
                        new
                        {
                            Id = new Guid("a06b2bca-9ab8-44b0-9cc5-d797c4692d32"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("1d1b397c-0d07-4398-aca7-5c7ea4d2ca12"),
                            RoomId = new Guid("664efd94-8791-47e0-93f5-a90471a719ce")
                        },
                        new
                        {
                            Id = new Guid("3006ad14-2617-427a-9f92-3d96d9125d0f"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("c526cd14-b087-4a47-b311-810d99134cd2"),
                            RoomId = new Guid("b64f485b-7269-428f-86b6-18644500d0c8")
                        },
                        new
                        {
                            Id = new Guid("c0d914ee-f519-44a4-a688-db16414b150b"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("6a9a0f85-fac2-4904-919e-be0d68e0e50a"),
                            RoomId = new Guid("b64f485b-7269-428f-86b6-18644500d0c8")
                        },
                        new
                        {
                            Id = new Guid("55eaa2a4-db6c-4e06-969e-450ed88fc4ab"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("3fa8ac09-db05-4ef5-b341-e003d132dc58"),
                            RoomId = new Guid("b64f485b-7269-428f-86b6-18644500d0c8")
                        },
                        new
                        {
                            Id = new Guid("4e9e314f-1c91-45fc-aff8-fac1bfcb862c"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("436f3b3b-171c-49c9-996a-dd3b29cea176"),
                            RoomId = new Guid("b64f485b-7269-428f-86b6-18644500d0c8")
                        },
                        new
                        {
                            Id = new Guid("0348f3b3-ec82-468f-8a40-ad65ba1546a9"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("accf4824-a50e-4122-9777-a826c75288f4"),
                            RoomId = new Guid("1263221d-1089-46de-8072-5a7841fb7ef2")
                        },
                        new
                        {
                            Id = new Guid("d94730d3-ba34-48f3-bd1c-6a54704cd3b3"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("1d1b397c-0d07-4398-aca7-5c7ea4d2ca12"),
                            RoomId = new Guid("1263221d-1089-46de-8072-5a7841fb7ef2")
                        },
                        new
                        {
                            Id = new Guid("49d40226-c63e-490b-9067-def030cbb7d6"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("c526cd14-b087-4a47-b311-810d99134cd2"),
                            RoomId = new Guid("1263221d-1089-46de-8072-5a7841fb7ef2")
                        },
                        new
                        {
                            Id = new Guid("572d7584-44f6-4286-80f9-aa2ddf5fad4f"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("6a9a0f85-fac2-4904-919e-be0d68e0e50a"),
                            RoomId = new Guid("1263221d-1089-46de-8072-5a7841fb7ef2")
                        },
                        new
                        {
                            Id = new Guid("284eaf12-adb7-41b5-85d6-5bc9fdbb3349"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("3fa8ac09-db05-4ef5-b341-e003d132dc58"),
                            RoomId = new Guid("1263221d-1089-46de-8072-5a7841fb7ef2")
                        },
                        new
                        {
                            Id = new Guid("ec2547e3-7df8-403d-a226-5368c2a225f1"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("38792418-a30d-483c-843c-3a072addabbc"),
                            RoomId = new Guid("1263221d-1089-46de-8072-5a7841fb7ef2")
                        },
                        new
                        {
                            Id = new Guid("ce76abad-12c9-405f-a0f5-817e1ef6383e"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("3fa8ac09-db05-4ef5-b341-e003d132dc58"),
                            RoomId = new Guid("0d9da574-4fd0-4392-9432-809db6df05f0")
                        },
                        new
                        {
                            Id = new Guid("648de209-d9be-4478-8754-8170580ee220"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("6a9a0f85-fac2-4904-919e-be0d68e0e50a"),
                            RoomId = new Guid("0d9da574-4fd0-4392-9432-809db6df05f0")
                        },
                        new
                        {
                            Id = new Guid("ced0a90c-4dfa-4550-b3be-b4454ef3c4e3"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("436f3b3b-171c-49c9-996a-dd3b29cea176"),
                            RoomId = new Guid("0d9da574-4fd0-4392-9432-809db6df05f0")
                        },
                        new
                        {
                            Id = new Guid("737f4005-68c7-42f0-b92c-c09e419f8032"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("1d1b397c-0d07-4398-aca7-5c7ea4d2ca12"),
                            RoomId = new Guid("b379d037-36eb-4a43-a2ad-df02ddd6c0c6")
                        },
                        new
                        {
                            Id = new Guid("aeaaf621-de28-40cf-a908-5c44eceaf4dc"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("accf4824-a50e-4122-9777-a826c75288f4"),
                            RoomId = new Guid("f233b8ba-f83e-4a93-900a-9011f74bf290")
                        },
                        new
                        {
                            Id = new Guid("3f4c7215-9149-4c42-a99c-5020bbf593ba"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("6a9a0f85-fac2-4904-919e-be0d68e0e50a"),
                            RoomId = new Guid("f233b8ba-f83e-4a93-900a-9011f74bf290")
                        },
                        new
                        {
                            Id = new Guid("385386df-05b3-48d8-a177-681f1726651a"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("38792418-a30d-483c-843c-3a072addabbc"),
                            RoomId = new Guid("f233b8ba-f83e-4a93-900a-9011f74bf290")
                        },
                        new
                        {
                            Id = new Guid("b1f248fc-6142-42d1-bbde-051d638ddc10"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("1d1b397c-0d07-4398-aca7-5c7ea4d2ca12"),
                            RoomId = new Guid("f233b8ba-f83e-4a93-900a-9011f74bf290")
                        },
                        new
                        {
                            Id = new Guid("88c3ed9f-ec98-4463-963e-28de85ca6c75"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("3fa8ac09-db05-4ef5-b341-e003d132dc58"),
                            RoomId = new Guid("f233b8ba-f83e-4a93-900a-9011f74bf290")
                        },
                        new
                        {
                            Id = new Guid("2178f6ff-e942-46a8-974e-1d4133bda5f8"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("436f3b3b-171c-49c9-996a-dd3b29cea176"),
                            RoomId = new Guid("f233b8ba-f83e-4a93-900a-9011f74bf290")
                        },
                        new
                        {
                            Id = new Guid("ee4d0c3e-9dbb-4f7a-a18f-c0d149050005"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("436f3b3b-171c-49c9-996a-dd3b29cea176"),
                            RoomId = new Guid("ea378932-757c-46eb-a9b7-074379b6c130")
                        },
                        new
                        {
                            Id = new Guid("26c8cd6a-abd5-448a-b3c9-ed1e84c18085"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("38792418-a30d-483c-843c-3a072addabbc"),
                            RoomId = new Guid("ea378932-757c-46eb-a9b7-074379b6c130")
                        },
                        new
                        {
                            Id = new Guid("d364cfc4-3a15-4d39-a31f-663f5ba95a37"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("accf4824-a50e-4122-9777-a826c75288f4"),
                            RoomId = new Guid("ea378932-757c-46eb-a9b7-074379b6c130")
                        },
                        new
                        {
                            Id = new Guid("e6f76fa2-25f8-476f-ae63-6b01c8996e67"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("1d1b397c-0d07-4398-aca7-5c7ea4d2ca12"),
                            RoomId = new Guid("ea378932-757c-46eb-a9b7-074379b6c130")
                        },
                        new
                        {
                            Id = new Guid("9afd5e35-b02e-41be-9777-e45947887bd8"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("c526cd14-b087-4a47-b311-810d99134cd2"),
                            RoomId = new Guid("ea378932-757c-46eb-a9b7-074379b6c130")
                        },
                        new
                        {
                            Id = new Guid("1a9c4085-e112-41bb-a4f4-dabf397cac6c"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("6a9a0f85-fac2-4904-919e-be0d68e0e50a"),
                            RoomId = new Guid("293f5ab3-f6a3-4456-9f07-0f4d4d879b17")
                        },
                        new
                        {
                            Id = new Guid("df8c3c64-218f-42f0-81d9-c62875ebb4c3"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("1d1b397c-0d07-4398-aca7-5c7ea4d2ca12"),
                            RoomId = new Guid("293f5ab3-f6a3-4456-9f07-0f4d4d879b17")
                        },
                        new
                        {
                            Id = new Guid("02b857ef-8951-4afe-8a45-f497c7e82ea2"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("38792418-a30d-483c-843c-3a072addabbc"),
                            RoomId = new Guid("293f5ab3-f6a3-4456-9f07-0f4d4d879b17")
                        },
                        new
                        {
                            Id = new Guid("564ec9fe-44ee-4d9a-92be-db9178bc06e5"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("3fa8ac09-db05-4ef5-b341-e003d132dc58"),
                            RoomId = new Guid("293f5ab3-f6a3-4456-9f07-0f4d4d879b17")
                        },
                        new
                        {
                            Id = new Guid("92299cbd-e4c5-4846-8894-cb117f12c6d4"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("436f3b3b-171c-49c9-996a-dd3b29cea176"),
                            RoomId = new Guid("293f5ab3-f6a3-4456-9f07-0f4d4d879b17")
                        },
                        new
                        {
                            Id = new Guid("a7c474ab-1b5c-4819-ac59-256b90742493"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("c526cd14-b087-4a47-b311-810d99134cd2"),
                            RoomId = new Guid("0f0c2db7-0760-4b68-a7ea-92ab8f02087b")
                        },
                        new
                        {
                            Id = new Guid("f05446e2-750e-4dfb-ae64-5e3d49abd266"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("3fa8ac09-db05-4ef5-b341-e003d132dc58"),
                            RoomId = new Guid("0f0c2db7-0760-4b68-a7ea-92ab8f02087b")
                        },
                        new
                        {
                            Id = new Guid("e8756169-ea27-4acb-bf40-aa6af23a9309"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("accf4824-a50e-4122-9777-a826c75288f4"),
                            RoomId = new Guid("0f0c2db7-0760-4b68-a7ea-92ab8f02087b")
                        },
                        new
                        {
                            Id = new Guid("46d50dd8-4429-41fb-814d-5e84d9f6b9dc"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("436f3b3b-171c-49c9-996a-dd3b29cea176"),
                            RoomId = new Guid("0f0c2db7-0760-4b68-a7ea-92ab8f02087b")
                        },
                        new
                        {
                            Id = new Guid("ed8df2ca-0f1f-45cd-a737-fbdfa0b8b600"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("38792418-a30d-483c-843c-3a072addabbc"),
                            RoomId = new Guid("0f0c2db7-0760-4b68-a7ea-92ab8f02087b")
                        },
                        new
                        {
                            Id = new Guid("02c32697-0203-4dd4-af1f-86b6aef7eac2"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("6a9a0f85-fac2-4904-919e-be0d68e0e50a"),
                            RoomId = new Guid("0f0c2db7-0760-4b68-a7ea-92ab8f02087b")
                        },
                        new
                        {
                            Id = new Guid("2746e348-f3ad-431b-a971-dd3f9d5108fa"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("3fa8ac09-db05-4ef5-b341-e003d132dc58"),
                            RoomId = new Guid("79551927-0e12-4f75-9806-98d4f76ccc2f")
                        },
                        new
                        {
                            Id = new Guid("d15e23d8-70a9-424d-8894-139e0c1d96cf"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("38792418-a30d-483c-843c-3a072addabbc"),
                            RoomId = new Guid("79551927-0e12-4f75-9806-98d4f76ccc2f")
                        },
                        new
                        {
                            Id = new Guid("87086ef7-5cae-4ad6-b5a0-daed009f602c"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("1d1b397c-0d07-4398-aca7-5c7ea4d2ca12"),
                            RoomId = new Guid("79551927-0e12-4f75-9806-98d4f76ccc2f")
                        },
                        new
                        {
                            Id = new Guid("79bc7164-aceb-49c0-81f6-5eb75f05bc21"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("436f3b3b-171c-49c9-996a-dd3b29cea176"),
                            RoomId = new Guid("79551927-0e12-4f75-9806-98d4f76ccc2f")
                        },
                        new
                        {
                            Id = new Guid("b18d39e6-bd34-49e4-bcbf-b997be561849"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("436f3b3b-171c-49c9-996a-dd3b29cea176"),
                            RoomId = new Guid("8db3a69a-e938-400a-b99b-1be55722a816")
                        },
                        new
                        {
                            Id = new Guid("39639cea-e888-4247-a883-0b1bfbd90f1f"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("1d1b397c-0d07-4398-aca7-5c7ea4d2ca12"),
                            RoomId = new Guid("8db3a69a-e938-400a-b99b-1be55722a816")
                        },
                        new
                        {
                            Id = new Guid("41de6083-cf03-40d4-b9d4-547300749280"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("3fa8ac09-db05-4ef5-b341-e003d132dc58"),
                            RoomId = new Guid("8db3a69a-e938-400a-b99b-1be55722a816")
                        },
                        new
                        {
                            Id = new Guid("cf42a7d8-41e9-4b99-ae58-06be48691245"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("c526cd14-b087-4a47-b311-810d99134cd2"),
                            RoomId = new Guid("8db3a69a-e938-400a-b99b-1be55722a816")
                        },
                        new
                        {
                            Id = new Guid("0eb12141-fcd7-4c91-abf8-4fe7b5d65300"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("accf4824-a50e-4122-9777-a826c75288f4"),
                            RoomId = new Guid("8db3a69a-e938-400a-b99b-1be55722a816")
                        },
                        new
                        {
                            Id = new Guid("852000a5-37a9-4fbe-8db6-7a731565bf95"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("6a9a0f85-fac2-4904-919e-be0d68e0e50a"),
                            RoomId = new Guid("8db3a69a-e938-400a-b99b-1be55722a816")
                        },
                        new
                        {
                            Id = new Guid("c967900d-76bd-4889-92a3-b722c002549c"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("38792418-a30d-483c-843c-3a072addabbc"),
                            RoomId = new Guid("1fb6e404-0af3-41a6-98c9-f97a8765d299")
                        },
                        new
                        {
                            Id = new Guid("ac94c1e4-c154-407e-88ee-93c7bc0d8fd9"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("6a9a0f85-fac2-4904-919e-be0d68e0e50a"),
                            RoomId = new Guid("1fb6e404-0af3-41a6-98c9-f97a8765d299")
                        },
                        new
                        {
                            Id = new Guid("9763326d-fec1-4da3-974b-a320af57059e"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("38792418-a30d-483c-843c-3a072addabbc"),
                            RoomId = new Guid("b9003860-62dd-42f5-b510-760d3e715ac2")
                        },
                        new
                        {
                            Id = new Guid("2817b1c9-0317-44f8-9933-a6fdf413a182"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("3fa8ac09-db05-4ef5-b341-e003d132dc58"),
                            RoomId = new Guid("b9003860-62dd-42f5-b510-760d3e715ac2")
                        },
                        new
                        {
                            Id = new Guid("8319ec5a-2f68-44ed-8d36-3e94fef5bcd2"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("accf4824-a50e-4122-9777-a826c75288f4"),
                            RoomId = new Guid("b9003860-62dd-42f5-b510-760d3e715ac2")
                        },
                        new
                        {
                            Id = new Guid("9d83f37f-0c88-4faa-b7e7-8533da8d2640"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("c526cd14-b087-4a47-b311-810d99134cd2"),
                            RoomId = new Guid("b9003860-62dd-42f5-b510-760d3e715ac2")
                        },
                        new
                        {
                            Id = new Guid("3d2dddf1-55af-4a42-965f-5e5487fdff21"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("1d1b397c-0d07-4398-aca7-5c7ea4d2ca12"),
                            RoomId = new Guid("b9003860-62dd-42f5-b510-760d3e715ac2")
                        },
                        new
                        {
                            Id = new Guid("3d461496-ea35-464c-9d2a-48e8fde67775"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("6a9a0f85-fac2-4904-919e-be0d68e0e50a"),
                            RoomId = new Guid("cb30ad96-44a2-4f05-9134-e891eb55177f")
                        },
                        new
                        {
                            Id = new Guid("d2a984f1-ee53-4997-827e-917e34a47780"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("38792418-a30d-483c-843c-3a072addabbc"),
                            RoomId = new Guid("cb30ad96-44a2-4f05-9134-e891eb55177f")
                        },
                        new
                        {
                            Id = new Guid("8144e92a-d43a-47e2-bd3c-73a46c5c62b5"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("accf4824-a50e-4122-9777-a826c75288f4"),
                            RoomId = new Guid("cb30ad96-44a2-4f05-9134-e891eb55177f")
                        },
                        new
                        {
                            Id = new Guid("beb2e52f-e57b-4d3f-92aa-085060ef9e54"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("38792418-a30d-483c-843c-3a072addabbc"),
                            RoomId = new Guid("a41f1d35-7849-47d8-9122-feebed9f0af2")
                        },
                        new
                        {
                            Id = new Guid("cbcd1414-197a-4366-9e26-bc90afcb807d"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("3fa8ac09-db05-4ef5-b341-e003d132dc58"),
                            RoomId = new Guid("a41f1d35-7849-47d8-9122-feebed9f0af2")
                        },
                        new
                        {
                            Id = new Guid("d056ff83-d7de-497e-bce0-e9bec270328c"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("accf4824-a50e-4122-9777-a826c75288f4"),
                            RoomId = new Guid("a41f1d35-7849-47d8-9122-feebed9f0af2")
                        },
                        new
                        {
                            Id = new Guid("c85aaf6c-063b-4ffd-9921-d0bbafa65956"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("1d1b397c-0d07-4398-aca7-5c7ea4d2ca12"),
                            RoomId = new Guid("a41f1d35-7849-47d8-9122-feebed9f0af2")
                        },
                        new
                        {
                            Id = new Guid("8e0e10a8-9e54-4a74-9ceb-686e2a6b261d"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("6a9a0f85-fac2-4904-919e-be0d68e0e50a"),
                            RoomId = new Guid("a41f1d35-7849-47d8-9122-feebed9f0af2")
                        },
                        new
                        {
                            Id = new Guid("2cbd6f57-f275-442a-8ccc-fb1f0ecab6cd"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("436f3b3b-171c-49c9-996a-dd3b29cea176"),
                            RoomId = new Guid("a41f1d35-7849-47d8-9122-feebed9f0af2")
                        },
                        new
                        {
                            Id = new Guid("dd1a1f3a-6d59-4435-82bf-2fbc4cd42088"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("accf4824-a50e-4122-9777-a826c75288f4"),
                            RoomId = new Guid("60104d45-1f95-47f7-ad6c-abbcfa3c5c5f")
                        },
                        new
                        {
                            Id = new Guid("381c302c-8e7c-4555-aba9-7a661b0c4045"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("3fa8ac09-db05-4ef5-b341-e003d132dc58"),
                            RoomId = new Guid("60104d45-1f95-47f7-ad6c-abbcfa3c5c5f")
                        },
                        new
                        {
                            Id = new Guid("86449c79-fe45-4df9-a064-2260d9c64b7e"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("6a9a0f85-fac2-4904-919e-be0d68e0e50a"),
                            RoomId = new Guid("0174d0fd-fba9-46bf-8eb3-c5152d0eaa38")
                        },
                        new
                        {
                            Id = new Guid("4de9c99d-84c5-4cf1-95ee-975843e74b22"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("6a9a0f85-fac2-4904-919e-be0d68e0e50a"),
                            RoomId = new Guid("f5af0699-4280-4c91-a8d7-05873ed37854")
                        },
                        new
                        {
                            Id = new Guid("f11cafd9-1dab-4520-acf4-beb721951e11"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("1d1b397c-0d07-4398-aca7-5c7ea4d2ca12"),
                            RoomId = new Guid("f5af0699-4280-4c91-a8d7-05873ed37854")
                        },
                        new
                        {
                            Id = new Guid("02712cb9-a446-440d-8b1e-0bcb169025cf"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("3fa8ac09-db05-4ef5-b341-e003d132dc58"),
                            RoomId = new Guid("f5af0699-4280-4c91-a8d7-05873ed37854")
                        },
                        new
                        {
                            Id = new Guid("25d5e69d-cca2-44ec-80bd-103c7d63aa5f"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("436f3b3b-171c-49c9-996a-dd3b29cea176"),
                            RoomId = new Guid("f5af0699-4280-4c91-a8d7-05873ed37854")
                        },
                        new
                        {
                            Id = new Guid("e048a3cb-f957-44b3-bdfb-a6f4eb906cc9"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("c526cd14-b087-4a47-b311-810d99134cd2"),
                            RoomId = new Guid("f5af0699-4280-4c91-a8d7-05873ed37854")
                        },
                        new
                        {
                            Id = new Guid("d86f6104-ab95-46af-a813-2c9702b7d8d0"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("1d1b397c-0d07-4398-aca7-5c7ea4d2ca12"),
                            RoomId = new Guid("c46a33c4-5aa5-4d99-83e8-6d266d94fe51")
                        },
                        new
                        {
                            Id = new Guid("0dcaec02-180e-4bec-86b3-c4d034d82e7f"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("38792418-a30d-483c-843c-3a072addabbc"),
                            RoomId = new Guid("c46a33c4-5aa5-4d99-83e8-6d266d94fe51")
                        },
                        new
                        {
                            Id = new Guid("bcf9eae5-d166-40d7-955d-a308b1d854db"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("436f3b3b-171c-49c9-996a-dd3b29cea176"),
                            RoomId = new Guid("c46a33c4-5aa5-4d99-83e8-6d266d94fe51")
                        },
                        new
                        {
                            Id = new Guid("9027e127-ed98-458a-8fda-cc2b8f4e1176"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("3fa8ac09-db05-4ef5-b341-e003d132dc58"),
                            RoomId = new Guid("c46a33c4-5aa5-4d99-83e8-6d266d94fe51")
                        },
                        new
                        {
                            Id = new Guid("2a46e0ba-44e7-40df-8595-bd62acb261d3"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("6a9a0f85-fac2-4904-919e-be0d68e0e50a"),
                            RoomId = new Guid("c46a33c4-5aa5-4d99-83e8-6d266d94fe51")
                        },
                        new
                        {
                            Id = new Guid("bbed5655-5e24-40b6-ad0d-7600218e5abc"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("c526cd14-b087-4a47-b311-810d99134cd2"),
                            RoomId = new Guid("c46a33c4-5aa5-4d99-83e8-6d266d94fe51")
                        },
                        new
                        {
                            Id = new Guid("a113e2bf-0019-4984-9076-84e9f2200639"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("accf4824-a50e-4122-9777-a826c75288f4"),
                            RoomId = new Guid("e62620f7-4612-4b62-98d5-bff192d83494")
                        },
                        new
                        {
                            Id = new Guid("363456f2-09a1-4a67-b080-eaef5466c10f"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("c526cd14-b087-4a47-b311-810d99134cd2"),
                            RoomId = new Guid("e62620f7-4612-4b62-98d5-bff192d83494")
                        },
                        new
                        {
                            Id = new Guid("4d4ca555-c078-4b31-9dae-f80f23cf0b02"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("1d1b397c-0d07-4398-aca7-5c7ea4d2ca12"),
                            RoomId = new Guid("e62620f7-4612-4b62-98d5-bff192d83494")
                        },
                        new
                        {
                            Id = new Guid("204ed047-4234-4f3d-bc34-1c59414d1560"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("6a9a0f85-fac2-4904-919e-be0d68e0e50a"),
                            RoomId = new Guid("43b1aadb-ced0-496a-b46a-f54732bf03eb")
                        },
                        new
                        {
                            Id = new Guid("6f8b3329-f493-437e-a049-eb40f806decc"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("3fa8ac09-db05-4ef5-b341-e003d132dc58"),
                            RoomId = new Guid("43b1aadb-ced0-496a-b46a-f54732bf03eb")
                        },
                        new
                        {
                            Id = new Guid("8ff00f11-b653-43f7-8d36-9a7b89cdcc8b"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("1d1b397c-0d07-4398-aca7-5c7ea4d2ca12"),
                            RoomId = new Guid("43b1aadb-ced0-496a-b46a-f54732bf03eb")
                        },
                        new
                        {
                            Id = new Guid("67f59894-2845-4a23-9b53-afdc0f9be685"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("436f3b3b-171c-49c9-996a-dd3b29cea176"),
                            RoomId = new Guid("43b1aadb-ced0-496a-b46a-f54732bf03eb")
                        },
                        new
                        {
                            Id = new Guid("e81966ed-cb11-45ba-919a-241e22951d60"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("accf4824-a50e-4122-9777-a826c75288f4"),
                            RoomId = new Guid("f77269e4-005e-41bb-bb4f-6f0c3bc07c78")
                        },
                        new
                        {
                            Id = new Guid("ba5408ca-a75b-4203-a8c8-4b47b63f4326"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("6a9a0f85-fac2-4904-919e-be0d68e0e50a"),
                            RoomId = new Guid("f77269e4-005e-41bb-bb4f-6f0c3bc07c78")
                        },
                        new
                        {
                            Id = new Guid("4dbef848-e038-4ff5-a9aa-a0c2eb16e7db"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("c526cd14-b087-4a47-b311-810d99134cd2"),
                            RoomId = new Guid("f77269e4-005e-41bb-bb4f-6f0c3bc07c78")
                        },
                        new
                        {
                            Id = new Guid("889ef833-82bd-4084-b76c-cbe2eda480a5"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("38792418-a30d-483c-843c-3a072addabbc"),
                            RoomId = new Guid("f77269e4-005e-41bb-bb4f-6f0c3bc07c78")
                        },
                        new
                        {
                            Id = new Guid("8dd1face-723d-4dea-96df-22e912a493cf"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("6a9a0f85-fac2-4904-919e-be0d68e0e50a"),
                            RoomId = new Guid("63c3b25f-c73e-4738-8d85-1e945ae8cea3")
                        },
                        new
                        {
                            Id = new Guid("18779bb3-ba10-4a5c-a50e-b1e71e9a0b8b"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("accf4824-a50e-4122-9777-a826c75288f4"),
                            RoomId = new Guid("63c3b25f-c73e-4738-8d85-1e945ae8cea3")
                        },
                        new
                        {
                            Id = new Guid("dff72f35-b429-4bcb-ba3a-77d0a887b273"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("3fa8ac09-db05-4ef5-b341-e003d132dc58"),
                            RoomId = new Guid("63c3b25f-c73e-4738-8d85-1e945ae8cea3")
                        },
                        new
                        {
                            Id = new Guid("285b8b20-25da-4328-acc7-2f69473e304a"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("38792418-a30d-483c-843c-3a072addabbc"),
                            RoomId = new Guid("63c3b25f-c73e-4738-8d85-1e945ae8cea3")
                        },
                        new
                        {
                            Id = new Guid("f1d7db20-64d2-407b-894c-47c489abaa27"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("6a9a0f85-fac2-4904-919e-be0d68e0e50a"),
                            RoomId = new Guid("735de6ab-bfd8-40c5-abd1-7706600bf428")
                        },
                        new
                        {
                            Id = new Guid("b6bdf50a-5529-4cdd-a7b5-7992c49f04dd"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("3fa8ac09-db05-4ef5-b341-e003d132dc58"),
                            RoomId = new Guid("735de6ab-bfd8-40c5-abd1-7706600bf428")
                        },
                        new
                        {
                            Id = new Guid("4a382dac-7b30-4f31-9ed1-0b0cba42a6c0"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("1d1b397c-0d07-4398-aca7-5c7ea4d2ca12"),
                            RoomId = new Guid("92701ba7-6787-44b2-ab2b-364e75f85730")
                        },
                        new
                        {
                            Id = new Guid("4f5e7a6f-820d-4455-8e89-fda01a784eee"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("3fa8ac09-db05-4ef5-b341-e003d132dc58"),
                            RoomId = new Guid("92701ba7-6787-44b2-ab2b-364e75f85730")
                        },
                        new
                        {
                            Id = new Guid("151fdb39-6ec8-4495-8c71-26435c412473"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("6a9a0f85-fac2-4904-919e-be0d68e0e50a"),
                            RoomId = new Guid("92701ba7-6787-44b2-ab2b-364e75f85730")
                        },
                        new
                        {
                            Id = new Guid("7c7b58d1-ae43-4ec8-821d-18d167c77368"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("38792418-a30d-483c-843c-3a072addabbc"),
                            RoomId = new Guid("92701ba7-6787-44b2-ab2b-364e75f85730")
                        },
                        new
                        {
                            Id = new Guid("d453eb12-334d-4543-b3f8-2a43ce42583b"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("436f3b3b-171c-49c9-996a-dd3b29cea176"),
                            RoomId = new Guid("92701ba7-6787-44b2-ab2b-364e75f85730")
                        },
                        new
                        {
                            Id = new Guid("34635b16-7c33-4749-9613-bd94edc1d27a"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("c526cd14-b087-4a47-b311-810d99134cd2"),
                            RoomId = new Guid("92701ba7-6787-44b2-ab2b-364e75f85730")
                        },
                        new
                        {
                            Id = new Guid("df770a8f-3132-4e57-a590-059b45c738ec"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("accf4824-a50e-4122-9777-a826c75288f4"),
                            RoomId = new Guid("4949b9c4-d8a1-4cf0-a875-5b52ae94ff91")
                        },
                        new
                        {
                            Id = new Guid("ff3b04cb-64d3-453e-be0b-621b8e0140dc"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("436f3b3b-171c-49c9-996a-dd3b29cea176"),
                            RoomId = new Guid("4949b9c4-d8a1-4cf0-a875-5b52ae94ff91")
                        },
                        new
                        {
                            Id = new Guid("a0362abe-4600-4969-b278-05dc82ee57ea"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("6a9a0f85-fac2-4904-919e-be0d68e0e50a"),
                            RoomId = new Guid("4949b9c4-d8a1-4cf0-a875-5b52ae94ff91")
                        },
                        new
                        {
                            Id = new Guid("a73c8147-1f42-4bbe-9b40-43c57f66cc17"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("38792418-a30d-483c-843c-3a072addabbc"),
                            RoomId = new Guid("4949b9c4-d8a1-4cf0-a875-5b52ae94ff91")
                        },
                        new
                        {
                            Id = new Guid("da2a6a49-cce3-4998-b0ac-5343618cd190"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("436f3b3b-171c-49c9-996a-dd3b29cea176"),
                            RoomId = new Guid("03e3c78c-343b-4836-bae3-207f9436ba17")
                        },
                        new
                        {
                            Id = new Guid("2f313ab4-77d1-4464-94c1-28538b37e9dc"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("accf4824-a50e-4122-9777-a826c75288f4"),
                            RoomId = new Guid("03e3c78c-343b-4836-bae3-207f9436ba17")
                        },
                        new
                        {
                            Id = new Guid("2133fad8-4275-4549-999d-0dfa5b039411"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("6a9a0f85-fac2-4904-919e-be0d68e0e50a"),
                            RoomId = new Guid("fddd9a83-f51d-4880-a4a0-79a97671b538")
                        },
                        new
                        {
                            Id = new Guid("ae1fa8f7-9cc3-43f1-b7eb-492fabadb8ae"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("38792418-a30d-483c-843c-3a072addabbc"),
                            RoomId = new Guid("fddd9a83-f51d-4880-a4a0-79a97671b538")
                        },
                        new
                        {
                            Id = new Guid("33d952a0-1fba-455f-ba10-aa7ee367e7b9"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("3fa8ac09-db05-4ef5-b341-e003d132dc58"),
                            RoomId = new Guid("fddd9a83-f51d-4880-a4a0-79a97671b538")
                        },
                        new
                        {
                            Id = new Guid("24367077-3967-45ec-93ac-fed749514441"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("accf4824-a50e-4122-9777-a826c75288f4"),
                            RoomId = new Guid("fddd9a83-f51d-4880-a4a0-79a97671b538")
                        },
                        new
                        {
                            Id = new Guid("0af7b0b8-69ef-4897-8782-95adc692dfac"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("c526cd14-b087-4a47-b311-810d99134cd2"),
                            RoomId = new Guid("fddd9a83-f51d-4880-a4a0-79a97671b538")
                        },
                        new
                        {
                            Id = new Guid("6f310106-f822-43b1-8bfc-2d847c2178ae"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("1d1b397c-0d07-4398-aca7-5c7ea4d2ca12"),
                            RoomId = new Guid("fddd9a83-f51d-4880-a4a0-79a97671b538")
                        },
                        new
                        {
                            Id = new Guid("802fde50-18cf-4147-ba91-b11d5b24ba64"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("1d1b397c-0d07-4398-aca7-5c7ea4d2ca12"),
                            RoomId = new Guid("1a024e28-3060-4d23-9c41-b5960c894f8f")
                        },
                        new
                        {
                            Id = new Guid("97a08d5e-3dd8-4f96-a965-d6f52cb99394"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("3fa8ac09-db05-4ef5-b341-e003d132dc58"),
                            RoomId = new Guid("1a024e28-3060-4d23-9c41-b5960c894f8f")
                        },
                        new
                        {
                            Id = new Guid("48db5631-18c4-401b-8422-e50ed68c1e6a"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("6a9a0f85-fac2-4904-919e-be0d68e0e50a"),
                            RoomId = new Guid("1a024e28-3060-4d23-9c41-b5960c894f8f")
                        },
                        new
                        {
                            Id = new Guid("d54bbfe3-7c60-4bb6-9d57-81cb3bc36336"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("accf4824-a50e-4122-9777-a826c75288f4"),
                            RoomId = new Guid("1a024e28-3060-4d23-9c41-b5960c894f8f")
                        },
                        new
                        {
                            Id = new Guid("9286580d-e8a1-4e55-85c1-e98690268d76"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("38792418-a30d-483c-843c-3a072addabbc"),
                            RoomId = new Guid("1a024e28-3060-4d23-9c41-b5960c894f8f")
                        },
                        new
                        {
                            Id = new Guid("1ebcab0e-4eb7-4f3f-b20c-f298f1e312c5"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("436f3b3b-171c-49c9-996a-dd3b29cea176"),
                            RoomId = new Guid("acf42373-049d-4b01-b60b-2ff4821f3991")
                        },
                        new
                        {
                            Id = new Guid("39bfd570-a6d9-4b02-bd39-68048b5c611f"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("3fa8ac09-db05-4ef5-b341-e003d132dc58"),
                            RoomId = new Guid("acf42373-049d-4b01-b60b-2ff4821f3991")
                        },
                        new
                        {
                            Id = new Guid("f79f16c7-0aa5-4d84-9ef9-c4528cd16e00"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("accf4824-a50e-4122-9777-a826c75288f4"),
                            RoomId = new Guid("acf42373-049d-4b01-b60b-2ff4821f3991")
                        },
                        new
                        {
                            Id = new Guid("06993abc-f971-41fd-a999-3b971751dc92"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("38792418-a30d-483c-843c-3a072addabbc"),
                            RoomId = new Guid("acf42373-049d-4b01-b60b-2ff4821f3991")
                        },
                        new
                        {
                            Id = new Guid("fb82ec05-81aa-45c2-9cb3-ed1d7cdfcae7"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("c526cd14-b087-4a47-b311-810d99134cd2"),
                            RoomId = new Guid("acf42373-049d-4b01-b60b-2ff4821f3991")
                        },
                        new
                        {
                            Id = new Guid("590f3876-7e85-49ae-a006-3d069ac2104e"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("6a9a0f85-fac2-4904-919e-be0d68e0e50a"),
                            RoomId = new Guid("acf42373-049d-4b01-b60b-2ff4821f3991")
                        },
                        new
                        {
                            Id = new Guid("4f368605-0738-4c9c-8518-7d3a4eea7256"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("6a9a0f85-fac2-4904-919e-be0d68e0e50a"),
                            RoomId = new Guid("07fe95f1-306c-42bc-a497-0f4975e86099")
                        },
                        new
                        {
                            Id = new Guid("f8eeabfa-1f3d-4e9a-a77f-5a9474c1568b"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("3fa8ac09-db05-4ef5-b341-e003d132dc58"),
                            RoomId = new Guid("07fe95f1-306c-42bc-a497-0f4975e86099")
                        },
                        new
                        {
                            Id = new Guid("6508bb62-ed6c-4134-a0ce-47803aa35a7d"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("c526cd14-b087-4a47-b311-810d99134cd2"),
                            RoomId = new Guid("07fe95f1-306c-42bc-a497-0f4975e86099")
                        },
                        new
                        {
                            Id = new Guid("a85238dd-50d5-4ae5-9cd3-a242fb549f75"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("436f3b3b-171c-49c9-996a-dd3b29cea176"),
                            RoomId = new Guid("c625aac5-d374-4c68-a883-4ee886edb9e4")
                        },
                        new
                        {
                            Id = new Guid("4de8b394-1996-480b-8f80-4fdf553f0ab5"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("38792418-a30d-483c-843c-3a072addabbc"),
                            RoomId = new Guid("c625aac5-d374-4c68-a883-4ee886edb9e4")
                        },
                        new
                        {
                            Id = new Guid("736fcf56-1abc-48ef-a469-f8a48fc29947"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("6a9a0f85-fac2-4904-919e-be0d68e0e50a"),
                            RoomId = new Guid("c625aac5-d374-4c68-a883-4ee886edb9e4")
                        },
                        new
                        {
                            Id = new Guid("31bb1106-50e5-48c0-be53-f8b1b2f74765"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("6a9a0f85-fac2-4904-919e-be0d68e0e50a"),
                            RoomId = new Guid("aae4ce69-2f3d-4dd8-9380-b1acf986f565")
                        },
                        new
                        {
                            Id = new Guid("1b0db42e-0a20-4bd3-8647-5574f6b91071"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("436f3b3b-171c-49c9-996a-dd3b29cea176"),
                            RoomId = new Guid("aae4ce69-2f3d-4dd8-9380-b1acf986f565")
                        },
                        new
                        {
                            Id = new Guid("bbc4b289-4d9a-46d8-8eb2-4af2cc660bad"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("c526cd14-b087-4a47-b311-810d99134cd2"),
                            RoomId = new Guid("3f3773d4-5437-46dd-8705-ad5c0e7df8aa")
                        },
                        new
                        {
                            Id = new Guid("5c7fb7c7-824d-41e8-b20f-9bc266b2141e"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("6a9a0f85-fac2-4904-919e-be0d68e0e50a"),
                            RoomId = new Guid("3f3773d4-5437-46dd-8705-ad5c0e7df8aa")
                        },
                        new
                        {
                            Id = new Guid("9c560e92-f895-4d46-abf1-1b82ff02e04f"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("38792418-a30d-483c-843c-3a072addabbc"),
                            RoomId = new Guid("3f3773d4-5437-46dd-8705-ad5c0e7df8aa")
                        },
                        new
                        {
                            Id = new Guid("9be7e501-d727-4e08-b450-07c9692c7fa7"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("accf4824-a50e-4122-9777-a826c75288f4"),
                            RoomId = new Guid("3f3773d4-5437-46dd-8705-ad5c0e7df8aa")
                        },
                        new
                        {
                            Id = new Guid("b4703892-5401-48de-9304-45277f0cc38e"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("c526cd14-b087-4a47-b311-810d99134cd2"),
                            RoomId = new Guid("75c5cd05-a06a-40ec-80bb-0d370ccd7327")
                        },
                        new
                        {
                            Id = new Guid("2b84507b-fc13-4a83-82ac-b793bc4b0d19"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("3fa8ac09-db05-4ef5-b341-e003d132dc58"),
                            RoomId = new Guid("75c5cd05-a06a-40ec-80bb-0d370ccd7327")
                        },
                        new
                        {
                            Id = new Guid("b67dd910-3f7b-4801-b311-e5572cd8b2ce"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("38792418-a30d-483c-843c-3a072addabbc"),
                            RoomId = new Guid("75c5cd05-a06a-40ec-80bb-0d370ccd7327")
                        },
                        new
                        {
                            Id = new Guid("04e18ddd-9575-41c3-960c-a99b60c566e4"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("1d1b397c-0d07-4398-aca7-5c7ea4d2ca12"),
                            RoomId = new Guid("75c5cd05-a06a-40ec-80bb-0d370ccd7327")
                        },
                        new
                        {
                            Id = new Guid("d4d6d824-48a0-4fbf-97f2-e41216ceab73"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("436f3b3b-171c-49c9-996a-dd3b29cea176"),
                            RoomId = new Guid("75c5cd05-a06a-40ec-80bb-0d370ccd7327")
                        },
                        new
                        {
                            Id = new Guid("aeda9529-9d87-4f65-ac24-fc1aa84d7d80"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("accf4824-a50e-4122-9777-a826c75288f4"),
                            RoomId = new Guid("75c5cd05-a06a-40ec-80bb-0d370ccd7327")
                        },
                        new
                        {
                            Id = new Guid("35f279fe-b6f7-40a2-8eb8-da3a981dec50"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("38792418-a30d-483c-843c-3a072addabbc"),
                            RoomId = new Guid("08c722d2-f819-4ef8-9441-fafc536a158a")
                        },
                        new
                        {
                            Id = new Guid("67d5a34b-540e-47e5-a265-e75997d367f0"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("1d1b397c-0d07-4398-aca7-5c7ea4d2ca12"),
                            RoomId = new Guid("08c722d2-f819-4ef8-9441-fafc536a158a")
                        },
                        new
                        {
                            Id = new Guid("131813ac-bfd5-435a-8e4b-9d7efe8fb8f1"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("6a9a0f85-fac2-4904-919e-be0d68e0e50a"),
                            RoomId = new Guid("08c722d2-f819-4ef8-9441-fafc536a158a")
                        },
                        new
                        {
                            Id = new Guid("1620f68e-d975-404d-aa15-cf3c167dfe47"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("accf4824-a50e-4122-9777-a826c75288f4"),
                            RoomId = new Guid("08c722d2-f819-4ef8-9441-fafc536a158a")
                        });
                });

            modelBuilder.Entity("DormitoryManagement.Data.Models.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RoomAssignmentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoomAssignmentId")
                        .IsUnique();

                    b.ToTable("Student");
                });

            modelBuilder.Entity("DormitoryManagement.Data.Models.Floor", b =>
                {
                    b.HasOne("DormitoryManagement.Data.Models.Building", "Building")
                        .WithMany("Floors")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("DormitoryManagement.Data.Models.Room", b =>
                {
                    b.HasOne("DormitoryManagement.Data.Models.Floor", "Floor")
                        .WithMany("Rooms")
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Floor");
                });

            modelBuilder.Entity("DormitoryManagement.Data.Models.RoomAssignment", b =>
                {
                    b.HasOne("DormitoryManagement.Data.Models.Room", "Room")
                        .WithMany("RoomAssignments")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("DormitoryManagement.Data.Models.RoomInventory", b =>
                {
                    b.HasOne("DormitoryManagement.Data.Models.InventoryItem", "InventoryItem")
                        .WithMany()
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DormitoryManagement.Data.Models.Room", "Room")
                        .WithMany("RoomInventories")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryItem");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("DormitoryManagement.Data.Models.Student", b =>
                {
                    b.HasOne("DormitoryManagement.Data.Models.RoomAssignment", "RoomAssignment")
                        .WithOne("Student")
                        .HasForeignKey("DormitoryManagement.Data.Models.Student", "RoomAssignmentId");

                    b.Navigation("RoomAssignment");
                });

            modelBuilder.Entity("DormitoryManagement.Data.Models.Building", b =>
                {
                    b.Navigation("Floors");
                });

            modelBuilder.Entity("DormitoryManagement.Data.Models.Floor", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("DormitoryManagement.Data.Models.Room", b =>
                {
                    b.Navigation("RoomAssignments");

                    b.Navigation("RoomInventories");
                });

            modelBuilder.Entity("DormitoryManagement.Data.Models.RoomAssignment", b =>
                {
                    b.Navigation("Student")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
