// <auto-generated />
using System;
using DormitoryManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DormitoryManagement.Migrations
{
    [DbContext(typeof(DormitoryContext))]
    partial class DormitoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DormitoryManagement.Data.Models.Building", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Buildings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("64931267-75af-438b-8e54-387b8ab3a976"),
                            Name = "Building A"
                        },
                        new
                        {
                            Id = new Guid("a6827413-fd8f-45ef-940b-68134b43aea8"),
                            Name = "Building B"
                        });
                });

            modelBuilder.Entity("DormitoryManagement.Data.Models.Floor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uuid");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("Floors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3f7106c2-8c3f-41dd-bc10-f2ea824abfef"),
                            BuildingId = new Guid("64931267-75af-438b-8e54-387b8ab3a976"),
                            Number = 1
                        },
                        new
                        {
                            Id = new Guid("e93588b8-6fab-450c-9803-30b20091f488"),
                            BuildingId = new Guid("64931267-75af-438b-8e54-387b8ab3a976"),
                            Number = 2
                        },
                        new
                        {
                            Id = new Guid("b9ee4f76-cd6e-4f25-bcf7-0601f8c8a39a"),
                            BuildingId = new Guid("a6827413-fd8f-45ef-940b-68134b43aea8"),
                            Number = 1
                        },
                        new
                        {
                            Id = new Guid("37753816-f2d0-4c9a-a83a-2f302480e1f2"),
                            BuildingId = new Guid("a6827413-fd8f-45ef-940b-68134b43aea8"),
                            Number = 2
                        });
                });

            modelBuilder.Entity("DormitoryManagement.Data.Models.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("InventoryItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3991ec86-1018-460a-8585-b1241983ca39"),
                            Name = "Chair"
                        },
                        new
                        {
                            Id = new Guid("65274cd8-ad94-46ce-ab22-85fccaef03a1"),
                            Name = "Desk"
                        },
                        new
                        {
                            Id = new Guid("40fab3cd-0be5-4aa5-af86-2d1f6c8d50f9"),
                            Name = "Bed"
                        },
                        new
                        {
                            Id = new Guid("134a9f90-fcd5-4be8-9fb1-e268ccf9702f"),
                            Name = "Lamp"
                        },
                        new
                        {
                            Id = new Guid("739d492c-6c54-40ee-ab83-c908b6465156"),
                            Name = "Bookshelf"
                        },
                        new
                        {
                            Id = new Guid("c0fa7802-39ec-4fae-bd7a-b0ac42ef0b10"),
                            Name = "Wardrobe"
                        },
                        new
                        {
                            Id = new Guid("27780236-fc1b-41e6-afb6-9ea50885658a"),
                            Name = "Curtains"
                        });
                });

            modelBuilder.Entity("DormitoryManagement.Data.Models.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AllowedPersons")
                        .HasColumnType("integer");

                    b.Property<Guid>("FloorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FloorId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f87c8718-f7cc-4a8f-b462-48eb6f0a6136"),
                            AllowedPersons = 4,
                            FloorId = new Guid("3f7106c2-8c3f-41dd-bc10-f2ea824abfef"),
                            Number = "A1-01"
                        },
                        new
                        {
                            Id = new Guid("fbad02b2-4ec2-48cf-8f8c-3f692296afcb"),
                            AllowedPersons = 5,
                            FloorId = new Guid("3f7106c2-8c3f-41dd-bc10-f2ea824abfef"),
                            Number = "A1-02"
                        },
                        new
                        {
                            Id = new Guid("7feb8f5a-f01c-4194-b0c5-80eedf5d841e"),
                            AllowedPersons = 5,
                            FloorId = new Guid("3f7106c2-8c3f-41dd-bc10-f2ea824abfef"),
                            Number = "A1-03"
                        },
                        new
                        {
                            Id = new Guid("e69a5bb6-af37-4358-be1d-1a442f7143bf"),
                            AllowedPersons = 5,
                            FloorId = new Guid("3f7106c2-8c3f-41dd-bc10-f2ea824abfef"),
                            Number = "A1-04"
                        },
                        new
                        {
                            Id = new Guid("ef4de191-ff71-4403-81a9-548742532a50"),
                            AllowedPersons = 3,
                            FloorId = new Guid("3f7106c2-8c3f-41dd-bc10-f2ea824abfef"),
                            Number = "A1-05"
                        },
                        new
                        {
                            Id = new Guid("19f07717-98b9-4f89-864f-018e1971dfda"),
                            AllowedPersons = 4,
                            FloorId = new Guid("3f7106c2-8c3f-41dd-bc10-f2ea824abfef"),
                            Number = "A1-06"
                        },
                        new
                        {
                            Id = new Guid("219aac27-50c6-419b-8eb1-745d85acdcf7"),
                            AllowedPersons = 4,
                            FloorId = new Guid("3f7106c2-8c3f-41dd-bc10-f2ea824abfef"),
                            Number = "A1-07"
                        },
                        new
                        {
                            Id = new Guid("ae733a14-4c92-4d9c-b54f-65530b82bc65"),
                            AllowedPersons = 4,
                            FloorId = new Guid("3f7106c2-8c3f-41dd-bc10-f2ea824abfef"),
                            Number = "A1-08"
                        },
                        new
                        {
                            Id = new Guid("9952d8c7-30f0-4055-8052-edbc1bd58bf7"),
                            AllowedPersons = 5,
                            FloorId = new Guid("3f7106c2-8c3f-41dd-bc10-f2ea824abfef"),
                            Number = "A1-09"
                        },
                        new
                        {
                            Id = new Guid("00898b02-d744-4140-875b-76ed5cdf42d7"),
                            AllowedPersons = 3,
                            FloorId = new Guid("3f7106c2-8c3f-41dd-bc10-f2ea824abfef"),
                            Number = "A1-10"
                        },
                        new
                        {
                            Id = new Guid("3d1a7f7b-7e0f-47af-8517-02969e507fe3"),
                            AllowedPersons = 4,
                            FloorId = new Guid("e93588b8-6fab-450c-9803-30b20091f488"),
                            Number = "A2-01"
                        },
                        new
                        {
                            Id = new Guid("568adfdb-5662-4d2c-894d-28f0dd639a42"),
                            AllowedPersons = 3,
                            FloorId = new Guid("e93588b8-6fab-450c-9803-30b20091f488"),
                            Number = "A2-02"
                        },
                        new
                        {
                            Id = new Guid("df86d717-cb3b-431b-91c8-9a9eaaa0659c"),
                            AllowedPersons = 3,
                            FloorId = new Guid("e93588b8-6fab-450c-9803-30b20091f488"),
                            Number = "A2-03"
                        },
                        new
                        {
                            Id = new Guid("08b7267f-7cfd-4150-9414-9793a6a263d4"),
                            AllowedPersons = 5,
                            FloorId = new Guid("e93588b8-6fab-450c-9803-30b20091f488"),
                            Number = "A2-04"
                        },
                        new
                        {
                            Id = new Guid("8f685e1a-8641-4116-8b5d-527a696deaf0"),
                            AllowedPersons = 3,
                            FloorId = new Guid("e93588b8-6fab-450c-9803-30b20091f488"),
                            Number = "A2-05"
                        },
                        new
                        {
                            Id = new Guid("803829fd-2cbd-4e16-9e82-a503832154b2"),
                            AllowedPersons = 3,
                            FloorId = new Guid("e93588b8-6fab-450c-9803-30b20091f488"),
                            Number = "A2-06"
                        },
                        new
                        {
                            Id = new Guid("db9d12ed-124b-433d-88cb-b7ee8cb78eee"),
                            AllowedPersons = 5,
                            FloorId = new Guid("e93588b8-6fab-450c-9803-30b20091f488"),
                            Number = "A2-07"
                        },
                        new
                        {
                            Id = new Guid("f8c0b71c-d966-42f0-b131-ab42952864c5"),
                            AllowedPersons = 5,
                            FloorId = new Guid("e93588b8-6fab-450c-9803-30b20091f488"),
                            Number = "A2-08"
                        },
                        new
                        {
                            Id = new Guid("117109ee-65cc-4d7c-b5bb-c2e6d618cb18"),
                            AllowedPersons = 5,
                            FloorId = new Guid("e93588b8-6fab-450c-9803-30b20091f488"),
                            Number = "A2-09"
                        },
                        new
                        {
                            Id = new Guid("406e45f3-07e1-4492-bec3-d7e908954561"),
                            AllowedPersons = 5,
                            FloorId = new Guid("e93588b8-6fab-450c-9803-30b20091f488"),
                            Number = "A2-10"
                        },
                        new
                        {
                            Id = new Guid("331e1d8c-8ae7-40ff-b6ef-1daf162b27d8"),
                            AllowedPersons = 5,
                            FloorId = new Guid("b9ee4f76-cd6e-4f25-bcf7-0601f8c8a39a"),
                            Number = "B1-01"
                        },
                        new
                        {
                            Id = new Guid("6647fd68-6211-48e1-9dba-dfd6720d31ab"),
                            AllowedPersons = 3,
                            FloorId = new Guid("b9ee4f76-cd6e-4f25-bcf7-0601f8c8a39a"),
                            Number = "B1-02"
                        },
                        new
                        {
                            Id = new Guid("3176f953-93dc-41d7-b2d6-5a047e61d327"),
                            AllowedPersons = 3,
                            FloorId = new Guid("b9ee4f76-cd6e-4f25-bcf7-0601f8c8a39a"),
                            Number = "B1-03"
                        },
                        new
                        {
                            Id = new Guid("44be5928-d56a-401f-abb5-fba4d864a21a"),
                            AllowedPersons = 5,
                            FloorId = new Guid("b9ee4f76-cd6e-4f25-bcf7-0601f8c8a39a"),
                            Number = "B1-04"
                        },
                        new
                        {
                            Id = new Guid("f81f2c9e-3b49-4168-a50c-98b96f2f44d7"),
                            AllowedPersons = 5,
                            FloorId = new Guid("b9ee4f76-cd6e-4f25-bcf7-0601f8c8a39a"),
                            Number = "B1-05"
                        },
                        new
                        {
                            Id = new Guid("1035b17f-89cd-4088-93d4-d1a85c6819d3"),
                            AllowedPersons = 4,
                            FloorId = new Guid("b9ee4f76-cd6e-4f25-bcf7-0601f8c8a39a"),
                            Number = "B1-06"
                        },
                        new
                        {
                            Id = new Guid("66e5b97d-6ccb-484e-a49e-ba1ee8550670"),
                            AllowedPersons = 5,
                            FloorId = new Guid("b9ee4f76-cd6e-4f25-bcf7-0601f8c8a39a"),
                            Number = "B1-07"
                        },
                        new
                        {
                            Id = new Guid("06685743-268b-49bf-9363-dcb7d0315cf3"),
                            AllowedPersons = 3,
                            FloorId = new Guid("b9ee4f76-cd6e-4f25-bcf7-0601f8c8a39a"),
                            Number = "B1-08"
                        },
                        new
                        {
                            Id = new Guid("036b910f-fb25-441f-a0e9-b089444d90da"),
                            AllowedPersons = 4,
                            FloorId = new Guid("b9ee4f76-cd6e-4f25-bcf7-0601f8c8a39a"),
                            Number = "B1-09"
                        },
                        new
                        {
                            Id = new Guid("a0d12b48-bbf0-471a-9ab1-adec22270ca9"),
                            AllowedPersons = 5,
                            FloorId = new Guid("b9ee4f76-cd6e-4f25-bcf7-0601f8c8a39a"),
                            Number = "B1-10"
                        },
                        new
                        {
                            Id = new Guid("8a56daf1-ef94-4ebd-a1d9-da1acc842104"),
                            AllowedPersons = 4,
                            FloorId = new Guid("37753816-f2d0-4c9a-a83a-2f302480e1f2"),
                            Number = "B2-01"
                        },
                        new
                        {
                            Id = new Guid("6ffbd267-b374-43cf-933c-5ad2a308f7d3"),
                            AllowedPersons = 3,
                            FloorId = new Guid("37753816-f2d0-4c9a-a83a-2f302480e1f2"),
                            Number = "B2-02"
                        },
                        new
                        {
                            Id = new Guid("eb5caa13-2962-41ae-9763-4c6cf4d9abad"),
                            AllowedPersons = 5,
                            FloorId = new Guid("37753816-f2d0-4c9a-a83a-2f302480e1f2"),
                            Number = "B2-03"
                        },
                        new
                        {
                            Id = new Guid("1787e7b2-e2ee-4d8f-93cb-e8f8a475fdb4"),
                            AllowedPersons = 3,
                            FloorId = new Guid("37753816-f2d0-4c9a-a83a-2f302480e1f2"),
                            Number = "B2-04"
                        },
                        new
                        {
                            Id = new Guid("8c6b81b2-e0ad-4247-9d13-225cf5aac8ef"),
                            AllowedPersons = 4,
                            FloorId = new Guid("37753816-f2d0-4c9a-a83a-2f302480e1f2"),
                            Number = "B2-05"
                        },
                        new
                        {
                            Id = new Guid("7555549e-1082-422e-9bcf-40ac3b0139c5"),
                            AllowedPersons = 4,
                            FloorId = new Guid("37753816-f2d0-4c9a-a83a-2f302480e1f2"),
                            Number = "B2-06"
                        },
                        new
                        {
                            Id = new Guid("95c91713-9525-441b-9c9e-9a9f2230d7f4"),
                            AllowedPersons = 4,
                            FloorId = new Guid("37753816-f2d0-4c9a-a83a-2f302480e1f2"),
                            Number = "B2-07"
                        },
                        new
                        {
                            Id = new Guid("ed001e85-d985-4609-8e7e-f291c15df380"),
                            AllowedPersons = 4,
                            FloorId = new Guid("37753816-f2d0-4c9a-a83a-2f302480e1f2"),
                            Number = "B2-08"
                        },
                        new
                        {
                            Id = new Guid("cf54b286-a6ba-43a6-bfe9-0358ce7c3642"),
                            AllowedPersons = 5,
                            FloorId = new Guid("37753816-f2d0-4c9a-a83a-2f302480e1f2"),
                            Number = "B2-09"
                        },
                        new
                        {
                            Id = new Guid("8ff91911-6c74-4b4d-8e93-91d4e580d1a1"),
                            AllowedPersons = 5,
                            FloorId = new Guid("37753816-f2d0-4c9a-a83a-2f302480e1f2"),
                            Number = "B2-10"
                        });
                });

            modelBuilder.Entity("DormitoryManagement.Data.Models.RoomAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomAssignment");
                });

            modelBuilder.Entity("DormitoryManagement.Data.Models.RoomInventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActualQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("ExpectedQuantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("InventoryItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InventoryItemId");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomInventories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8d7498b2-7525-42ee-8782-0e45e4de7178"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("65274cd8-ad94-46ce-ab22-85fccaef03a1"),
                            RoomId = new Guid("f87c8718-f7cc-4a8f-b462-48eb6f0a6136")
                        },
                        new
                        {
                            Id = new Guid("f46348cb-5f4f-4344-bbc1-fbb638a643be"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("134a9f90-fcd5-4be8-9fb1-e268ccf9702f"),
                            RoomId = new Guid("f87c8718-f7cc-4a8f-b462-48eb6f0a6136")
                        },
                        new
                        {
                            Id = new Guid("333124ef-cfde-4758-b402-79422b0ce029"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("27780236-fc1b-41e6-afb6-9ea50885658a"),
                            RoomId = new Guid("f87c8718-f7cc-4a8f-b462-48eb6f0a6136")
                        },
                        new
                        {
                            Id = new Guid("2b555ba6-2f82-4e7b-a3ec-11244cc48100"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("c0fa7802-39ec-4fae-bd7a-b0ac42ef0b10"),
                            RoomId = new Guid("fbad02b2-4ec2-48cf-8f8c-3f692296afcb")
                        },
                        new
                        {
                            Id = new Guid("8fa73d1d-69df-4844-9146-f320464acea9"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("40fab3cd-0be5-4aa5-af86-2d1f6c8d50f9"),
                            RoomId = new Guid("7feb8f5a-f01c-4194-b0c5-80eedf5d841e")
                        },
                        new
                        {
                            Id = new Guid("decef60c-afb7-4b0e-8827-bfa4167f64cf"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("134a9f90-fcd5-4be8-9fb1-e268ccf9702f"),
                            RoomId = new Guid("7feb8f5a-f01c-4194-b0c5-80eedf5d841e")
                        },
                        new
                        {
                            Id = new Guid("1ea3a8ca-85d9-4016-bef1-c0678a0b1187"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("739d492c-6c54-40ee-ab83-c908b6465156"),
                            RoomId = new Guid("7feb8f5a-f01c-4194-b0c5-80eedf5d841e")
                        },
                        new
                        {
                            Id = new Guid("11d6b0a2-57e8-4a43-8f98-6fcb258fe84b"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("65274cd8-ad94-46ce-ab22-85fccaef03a1"),
                            RoomId = new Guid("7feb8f5a-f01c-4194-b0c5-80eedf5d841e")
                        },
                        new
                        {
                            Id = new Guid("7e89739e-0183-4b47-8643-9910edd38716"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("c0fa7802-39ec-4fae-bd7a-b0ac42ef0b10"),
                            RoomId = new Guid("7feb8f5a-f01c-4194-b0c5-80eedf5d841e")
                        },
                        new
                        {
                            Id = new Guid("6fd663e7-7b9d-4d58-9421-66c583c03128"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("3991ec86-1018-460a-8585-b1241983ca39"),
                            RoomId = new Guid("e69a5bb6-af37-4358-be1d-1a442f7143bf")
                        },
                        new
                        {
                            Id = new Guid("46df8ce9-d3df-4dec-8590-82c8ec5598b4"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("739d492c-6c54-40ee-ab83-c908b6465156"),
                            RoomId = new Guid("e69a5bb6-af37-4358-be1d-1a442f7143bf")
                        },
                        new
                        {
                            Id = new Guid("ab5431a9-330d-45b0-8ad6-2446301aac13"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("c0fa7802-39ec-4fae-bd7a-b0ac42ef0b10"),
                            RoomId = new Guid("e69a5bb6-af37-4358-be1d-1a442f7143bf")
                        },
                        new
                        {
                            Id = new Guid("00e00d89-4b8a-45fa-96b7-2f1fad586391"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("65274cd8-ad94-46ce-ab22-85fccaef03a1"),
                            RoomId = new Guid("e69a5bb6-af37-4358-be1d-1a442f7143bf")
                        },
                        new
                        {
                            Id = new Guid("d0de26ba-a864-4146-b0ab-d10810321b0e"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("40fab3cd-0be5-4aa5-af86-2d1f6c8d50f9"),
                            RoomId = new Guid("e69a5bb6-af37-4358-be1d-1a442f7143bf")
                        },
                        new
                        {
                            Id = new Guid("ec5b9fb8-5351-4821-a058-a88393f70c08"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("134a9f90-fcd5-4be8-9fb1-e268ccf9702f"),
                            RoomId = new Guid("ef4de191-ff71-4403-81a9-548742532a50")
                        },
                        new
                        {
                            Id = new Guid("3c9c4c6f-27b6-4fcc-9e2e-fc0d4eddab67"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("65274cd8-ad94-46ce-ab22-85fccaef03a1"),
                            RoomId = new Guid("ef4de191-ff71-4403-81a9-548742532a50")
                        },
                        new
                        {
                            Id = new Guid("c714b960-764b-406e-802e-36af9b75c33c"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("40fab3cd-0be5-4aa5-af86-2d1f6c8d50f9"),
                            RoomId = new Guid("19f07717-98b9-4f89-864f-018e1971dfda")
                        },
                        new
                        {
                            Id = new Guid("00d23b47-dc89-4756-804d-ffc21d88e9cc"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("134a9f90-fcd5-4be8-9fb1-e268ccf9702f"),
                            RoomId = new Guid("19f07717-98b9-4f89-864f-018e1971dfda")
                        },
                        new
                        {
                            Id = new Guid("1986f9ef-25a6-4fe0-9fc9-117a5a13f3e1"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("739d492c-6c54-40ee-ab83-c908b6465156"),
                            RoomId = new Guid("19f07717-98b9-4f89-864f-018e1971dfda")
                        },
                        new
                        {
                            Id = new Guid("6cec1cc8-e187-49bd-8341-1ef3ea12ac3a"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("40fab3cd-0be5-4aa5-af86-2d1f6c8d50f9"),
                            RoomId = new Guid("219aac27-50c6-419b-8eb1-745d85acdcf7")
                        },
                        new
                        {
                            Id = new Guid("4012030e-aa71-4db8-9515-2cece90d9a01"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("3991ec86-1018-460a-8585-b1241983ca39"),
                            RoomId = new Guid("219aac27-50c6-419b-8eb1-745d85acdcf7")
                        },
                        new
                        {
                            Id = new Guid("ec43c6a4-208f-4482-93b5-164ba41bdd99"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("c0fa7802-39ec-4fae-bd7a-b0ac42ef0b10"),
                            RoomId = new Guid("ae733a14-4c92-4d9c-b54f-65530b82bc65")
                        },
                        new
                        {
                            Id = new Guid("4b01cf2b-850c-4305-94c8-ed69817fb9e1"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("134a9f90-fcd5-4be8-9fb1-e268ccf9702f"),
                            RoomId = new Guid("ae733a14-4c92-4d9c-b54f-65530b82bc65")
                        },
                        new
                        {
                            Id = new Guid("da5871cf-fc12-4317-a578-cfcbbab7d3a8"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("3991ec86-1018-460a-8585-b1241983ca39"),
                            RoomId = new Guid("9952d8c7-30f0-4055-8052-edbc1bd58bf7")
                        },
                        new
                        {
                            Id = new Guid("b008eb4b-1fde-46c4-85c0-bd1cb01945b3"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("134a9f90-fcd5-4be8-9fb1-e268ccf9702f"),
                            RoomId = new Guid("00898b02-d744-4140-875b-76ed5cdf42d7")
                        },
                        new
                        {
                            Id = new Guid("2a71a167-33d7-425c-9cbe-16724351fa76"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("739d492c-6c54-40ee-ab83-c908b6465156"),
                            RoomId = new Guid("00898b02-d744-4140-875b-76ed5cdf42d7")
                        },
                        new
                        {
                            Id = new Guid("7b1e634f-ec3d-4027-9686-95c519bc1426"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("65274cd8-ad94-46ce-ab22-85fccaef03a1"),
                            RoomId = new Guid("00898b02-d744-4140-875b-76ed5cdf42d7")
                        },
                        new
                        {
                            Id = new Guid("afce1d3f-f830-416e-b64a-b17ea955c756"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("3991ec86-1018-460a-8585-b1241983ca39"),
                            RoomId = new Guid("00898b02-d744-4140-875b-76ed5cdf42d7")
                        },
                        new
                        {
                            Id = new Guid("5acb7dea-9e17-478d-8dca-d2da1744a268"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("c0fa7802-39ec-4fae-bd7a-b0ac42ef0b10"),
                            RoomId = new Guid("3d1a7f7b-7e0f-47af-8517-02969e507fe3")
                        },
                        new
                        {
                            Id = new Guid("b5e159bc-b58a-4ce0-9747-962268bfe63f"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("40fab3cd-0be5-4aa5-af86-2d1f6c8d50f9"),
                            RoomId = new Guid("3d1a7f7b-7e0f-47af-8517-02969e507fe3")
                        },
                        new
                        {
                            Id = new Guid("84b69f01-96fb-4831-ad55-c691a254f214"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("739d492c-6c54-40ee-ab83-c908b6465156"),
                            RoomId = new Guid("3d1a7f7b-7e0f-47af-8517-02969e507fe3")
                        },
                        new
                        {
                            Id = new Guid("f5cb4736-389b-4ccc-9525-a3b3826882a6"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("c0fa7802-39ec-4fae-bd7a-b0ac42ef0b10"),
                            RoomId = new Guid("568adfdb-5662-4d2c-894d-28f0dd639a42")
                        },
                        new
                        {
                            Id = new Guid("665e81f9-9f74-429c-8f7c-07f36fd23e6f"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("3991ec86-1018-460a-8585-b1241983ca39"),
                            RoomId = new Guid("568adfdb-5662-4d2c-894d-28f0dd639a42")
                        },
                        new
                        {
                            Id = new Guid("8e3771f5-7e31-454f-989c-4aa7d3458f46"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("65274cd8-ad94-46ce-ab22-85fccaef03a1"),
                            RoomId = new Guid("568adfdb-5662-4d2c-894d-28f0dd639a42")
                        },
                        new
                        {
                            Id = new Guid("48dc4db4-f9f8-4193-8ce0-f674bf3197d4"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("40fab3cd-0be5-4aa5-af86-2d1f6c8d50f9"),
                            RoomId = new Guid("568adfdb-5662-4d2c-894d-28f0dd639a42")
                        },
                        new
                        {
                            Id = new Guid("4a214857-756c-40e9-ace9-e51e536e00e7"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("65274cd8-ad94-46ce-ab22-85fccaef03a1"),
                            RoomId = new Guid("df86d717-cb3b-431b-91c8-9a9eaaa0659c")
                        },
                        new
                        {
                            Id = new Guid("51b0451e-2c08-464c-b51d-901a3ac035e3"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("3991ec86-1018-460a-8585-b1241983ca39"),
                            RoomId = new Guid("08b7267f-7cfd-4150-9414-9793a6a263d4")
                        },
                        new
                        {
                            Id = new Guid("9cebaac6-6b73-441b-a2fb-b8caac6529c3"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("27780236-fc1b-41e6-afb6-9ea50885658a"),
                            RoomId = new Guid("08b7267f-7cfd-4150-9414-9793a6a263d4")
                        },
                        new
                        {
                            Id = new Guid("f249058b-53f8-429a-8346-281cc8a91cca"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("65274cd8-ad94-46ce-ab22-85fccaef03a1"),
                            RoomId = new Guid("08b7267f-7cfd-4150-9414-9793a6a263d4")
                        },
                        new
                        {
                            Id = new Guid("ddb09fa6-1f78-4c9b-8e2c-f58284828fdf"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("739d492c-6c54-40ee-ab83-c908b6465156"),
                            RoomId = new Guid("8f685e1a-8641-4116-8b5d-527a696deaf0")
                        },
                        new
                        {
                            Id = new Guid("098377d2-a513-4ba7-bc87-6e7cceceeda8"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("65274cd8-ad94-46ce-ab22-85fccaef03a1"),
                            RoomId = new Guid("803829fd-2cbd-4e16-9e82-a503832154b2")
                        },
                        new
                        {
                            Id = new Guid("7efaaac9-84fa-4988-8a28-f71c7c5b5448"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("3991ec86-1018-460a-8585-b1241983ca39"),
                            RoomId = new Guid("803829fd-2cbd-4e16-9e82-a503832154b2")
                        },
                        new
                        {
                            Id = new Guid("7d1fc29c-52be-455a-b9c3-7c39c4546be1"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("3991ec86-1018-460a-8585-b1241983ca39"),
                            RoomId = new Guid("db9d12ed-124b-433d-88cb-b7ee8cb78eee")
                        },
                        new
                        {
                            Id = new Guid("a41a128f-a0b4-4504-8963-d2d522c0739f"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("65274cd8-ad94-46ce-ab22-85fccaef03a1"),
                            RoomId = new Guid("db9d12ed-124b-433d-88cb-b7ee8cb78eee")
                        },
                        new
                        {
                            Id = new Guid("a3d3dab1-ea2b-4252-88ea-b4f9d91402a1"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("c0fa7802-39ec-4fae-bd7a-b0ac42ef0b10"),
                            RoomId = new Guid("f8c0b71c-d966-42f0-b131-ab42952864c5")
                        },
                        new
                        {
                            Id = new Guid("406f4923-845f-4b69-bbc5-8a92d9683d14"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("739d492c-6c54-40ee-ab83-c908b6465156"),
                            RoomId = new Guid("f8c0b71c-d966-42f0-b131-ab42952864c5")
                        },
                        new
                        {
                            Id = new Guid("9ff22a19-9a43-4529-976b-1c3e68d6e283"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("3991ec86-1018-460a-8585-b1241983ca39"),
                            RoomId = new Guid("f8c0b71c-d966-42f0-b131-ab42952864c5")
                        },
                        new
                        {
                            Id = new Guid("75ffad6b-0709-468c-b61e-30917ae20370"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("134a9f90-fcd5-4be8-9fb1-e268ccf9702f"),
                            RoomId = new Guid("f8c0b71c-d966-42f0-b131-ab42952864c5")
                        },
                        new
                        {
                            Id = new Guid("ef8cc41a-240b-4482-9bd0-aeaa3747d4b1"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("c0fa7802-39ec-4fae-bd7a-b0ac42ef0b10"),
                            RoomId = new Guid("117109ee-65cc-4d7c-b5bb-c2e6d618cb18")
                        },
                        new
                        {
                            Id = new Guid("dec30136-fd66-4ee1-b800-8f9a9d4b1517"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("739d492c-6c54-40ee-ab83-c908b6465156"),
                            RoomId = new Guid("117109ee-65cc-4d7c-b5bb-c2e6d618cb18")
                        },
                        new
                        {
                            Id = new Guid("09e14fff-651b-440c-aa89-0202712bd354"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("27780236-fc1b-41e6-afb6-9ea50885658a"),
                            RoomId = new Guid("117109ee-65cc-4d7c-b5bb-c2e6d618cb18")
                        },
                        new
                        {
                            Id = new Guid("9b3af33e-4014-4d2f-8be2-c7c008b7314e"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("27780236-fc1b-41e6-afb6-9ea50885658a"),
                            RoomId = new Guid("406e45f3-07e1-4492-bec3-d7e908954561")
                        },
                        new
                        {
                            Id = new Guid("753d4120-ea36-4c2a-879a-f61673165d7a"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("c0fa7802-39ec-4fae-bd7a-b0ac42ef0b10"),
                            RoomId = new Guid("406e45f3-07e1-4492-bec3-d7e908954561")
                        },
                        new
                        {
                            Id = new Guid("60ea6986-21dd-4791-8f0d-eb910bed93bf"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("65274cd8-ad94-46ce-ab22-85fccaef03a1"),
                            RoomId = new Guid("406e45f3-07e1-4492-bec3-d7e908954561")
                        },
                        new
                        {
                            Id = new Guid("bef3330a-9add-4ab8-bd64-dc60189bd6d1"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("739d492c-6c54-40ee-ab83-c908b6465156"),
                            RoomId = new Guid("406e45f3-07e1-4492-bec3-d7e908954561")
                        },
                        new
                        {
                            Id = new Guid("9955954b-8ed5-45c1-8536-e9920e139617"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("134a9f90-fcd5-4be8-9fb1-e268ccf9702f"),
                            RoomId = new Guid("406e45f3-07e1-4492-bec3-d7e908954561")
                        },
                        new
                        {
                            Id = new Guid("55a6d254-857b-490e-a616-826e7dba9216"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("3991ec86-1018-460a-8585-b1241983ca39"),
                            RoomId = new Guid("406e45f3-07e1-4492-bec3-d7e908954561")
                        },
                        new
                        {
                            Id = new Guid("89e8c38f-0e59-443e-afcf-fe466bbebc2b"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("40fab3cd-0be5-4aa5-af86-2d1f6c8d50f9"),
                            RoomId = new Guid("331e1d8c-8ae7-40ff-b6ef-1daf162b27d8")
                        },
                        new
                        {
                            Id = new Guid("77aae4cc-0c08-43f4-933b-f124c65c98c3"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("3991ec86-1018-460a-8585-b1241983ca39"),
                            RoomId = new Guid("331e1d8c-8ae7-40ff-b6ef-1daf162b27d8")
                        },
                        new
                        {
                            Id = new Guid("1ffa349b-bff3-4209-854f-c51365313e4e"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("c0fa7802-39ec-4fae-bd7a-b0ac42ef0b10"),
                            RoomId = new Guid("331e1d8c-8ae7-40ff-b6ef-1daf162b27d8")
                        },
                        new
                        {
                            Id = new Guid("fce9f330-3dcf-4fed-b896-567492a9bcab"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("65274cd8-ad94-46ce-ab22-85fccaef03a1"),
                            RoomId = new Guid("331e1d8c-8ae7-40ff-b6ef-1daf162b27d8")
                        },
                        new
                        {
                            Id = new Guid("aa62a1b4-0c3b-4bbf-9cde-052fc58ddb52"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("134a9f90-fcd5-4be8-9fb1-e268ccf9702f"),
                            RoomId = new Guid("331e1d8c-8ae7-40ff-b6ef-1daf162b27d8")
                        },
                        new
                        {
                            Id = new Guid("3f6e7bc8-f5a7-491f-9620-782e1eb48d8f"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("739d492c-6c54-40ee-ab83-c908b6465156"),
                            RoomId = new Guid("331e1d8c-8ae7-40ff-b6ef-1daf162b27d8")
                        },
                        new
                        {
                            Id = new Guid("b8e30cc3-4f01-4fbc-81dd-cbd73913e9f4"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("27780236-fc1b-41e6-afb6-9ea50885658a"),
                            RoomId = new Guid("6647fd68-6211-48e1-9dba-dfd6720d31ab")
                        },
                        new
                        {
                            Id = new Guid("b85a2bea-2cc8-4c5b-9539-7e16d1e1bcb0"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("c0fa7802-39ec-4fae-bd7a-b0ac42ef0b10"),
                            RoomId = new Guid("6647fd68-6211-48e1-9dba-dfd6720d31ab")
                        },
                        new
                        {
                            Id = new Guid("cb799c57-3738-4b14-93f7-f4e6379af05e"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("134a9f90-fcd5-4be8-9fb1-e268ccf9702f"),
                            RoomId = new Guid("6647fd68-6211-48e1-9dba-dfd6720d31ab")
                        },
                        new
                        {
                            Id = new Guid("cba883ff-0348-4850-bf21-6f404da0be00"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("739d492c-6c54-40ee-ab83-c908b6465156"),
                            RoomId = new Guid("6647fd68-6211-48e1-9dba-dfd6720d31ab")
                        },
                        new
                        {
                            Id = new Guid("ae07f59a-566c-4f08-855b-aa62000b8f17"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("40fab3cd-0be5-4aa5-af86-2d1f6c8d50f9"),
                            RoomId = new Guid("6647fd68-6211-48e1-9dba-dfd6720d31ab")
                        },
                        new
                        {
                            Id = new Guid("c3a7be87-e945-4875-9af1-0c6911bbfe04"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("65274cd8-ad94-46ce-ab22-85fccaef03a1"),
                            RoomId = new Guid("6647fd68-6211-48e1-9dba-dfd6720d31ab")
                        },
                        new
                        {
                            Id = new Guid("87f801cd-da22-460d-b809-de2312df5e3e"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("27780236-fc1b-41e6-afb6-9ea50885658a"),
                            RoomId = new Guid("3176f953-93dc-41d7-b2d6-5a047e61d327")
                        },
                        new
                        {
                            Id = new Guid("bca08a8c-6418-49a8-a055-3e257a7b3090"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("739d492c-6c54-40ee-ab83-c908b6465156"),
                            RoomId = new Guid("3176f953-93dc-41d7-b2d6-5a047e61d327")
                        },
                        new
                        {
                            Id = new Guid("7c1e560d-d2d4-49ce-9cf1-62d0989130dd"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("134a9f90-fcd5-4be8-9fb1-e268ccf9702f"),
                            RoomId = new Guid("3176f953-93dc-41d7-b2d6-5a047e61d327")
                        },
                        new
                        {
                            Id = new Guid("b6730931-f1f4-4773-82fc-5446e9ca91f3"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("65274cd8-ad94-46ce-ab22-85fccaef03a1"),
                            RoomId = new Guid("3176f953-93dc-41d7-b2d6-5a047e61d327")
                        },
                        new
                        {
                            Id = new Guid("6b8d8af5-5b43-4c79-b09d-77f6058bd50f"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("65274cd8-ad94-46ce-ab22-85fccaef03a1"),
                            RoomId = new Guid("44be5928-d56a-401f-abb5-fba4d864a21a")
                        },
                        new
                        {
                            Id = new Guid("63b87751-af4a-4865-8dc9-54d2d4e9162e"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("40fab3cd-0be5-4aa5-af86-2d1f6c8d50f9"),
                            RoomId = new Guid("f81f2c9e-3b49-4168-a50c-98b96f2f44d7")
                        },
                        new
                        {
                            Id = new Guid("768fa0fc-6c9b-4ea5-91d7-f2a684993306"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("27780236-fc1b-41e6-afb6-9ea50885658a"),
                            RoomId = new Guid("f81f2c9e-3b49-4168-a50c-98b96f2f44d7")
                        },
                        new
                        {
                            Id = new Guid("f65c1436-2c6d-4d9d-9176-67da937da2cf"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("c0fa7802-39ec-4fae-bd7a-b0ac42ef0b10"),
                            RoomId = new Guid("f81f2c9e-3b49-4168-a50c-98b96f2f44d7")
                        },
                        new
                        {
                            Id = new Guid("bfbee352-9435-4234-ac8e-7a47955b2f24"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("739d492c-6c54-40ee-ab83-c908b6465156"),
                            RoomId = new Guid("f81f2c9e-3b49-4168-a50c-98b96f2f44d7")
                        },
                        new
                        {
                            Id = new Guid("b4cd003f-8ef3-4343-9fcd-c4f3f29b5b87"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("3991ec86-1018-460a-8585-b1241983ca39"),
                            RoomId = new Guid("1035b17f-89cd-4088-93d4-d1a85c6819d3")
                        },
                        new
                        {
                            Id = new Guid("692af458-1fe0-4b87-8cbf-4d7285d53d05"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("27780236-fc1b-41e6-afb6-9ea50885658a"),
                            RoomId = new Guid("1035b17f-89cd-4088-93d4-d1a85c6819d3")
                        },
                        new
                        {
                            Id = new Guid("3143f432-32ae-484d-a50b-947b806a2efd"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("c0fa7802-39ec-4fae-bd7a-b0ac42ef0b10"),
                            RoomId = new Guid("1035b17f-89cd-4088-93d4-d1a85c6819d3")
                        },
                        new
                        {
                            Id = new Guid("50db1ed1-3501-4263-a5cc-8fa2a253420d"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("134a9f90-fcd5-4be8-9fb1-e268ccf9702f"),
                            RoomId = new Guid("66e5b97d-6ccb-484e-a49e-ba1ee8550670")
                        },
                        new
                        {
                            Id = new Guid("13eadcfb-6aa9-4d80-86a0-efc24df44c64"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("739d492c-6c54-40ee-ab83-c908b6465156"),
                            RoomId = new Guid("66e5b97d-6ccb-484e-a49e-ba1ee8550670")
                        },
                        new
                        {
                            Id = new Guid("c9a218aa-867a-414b-9259-819bed9d34b8"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("c0fa7802-39ec-4fae-bd7a-b0ac42ef0b10"),
                            RoomId = new Guid("66e5b97d-6ccb-484e-a49e-ba1ee8550670")
                        },
                        new
                        {
                            Id = new Guid("54565296-ac28-43ef-bb66-ae604fb5d226"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("40fab3cd-0be5-4aa5-af86-2d1f6c8d50f9"),
                            RoomId = new Guid("66e5b97d-6ccb-484e-a49e-ba1ee8550670")
                        },
                        new
                        {
                            Id = new Guid("e1b20880-60eb-468b-bc77-ebca50481963"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("65274cd8-ad94-46ce-ab22-85fccaef03a1"),
                            RoomId = new Guid("66e5b97d-6ccb-484e-a49e-ba1ee8550670")
                        },
                        new
                        {
                            Id = new Guid("498ef21f-d982-43e7-8404-86557c203855"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("65274cd8-ad94-46ce-ab22-85fccaef03a1"),
                            RoomId = new Guid("06685743-268b-49bf-9363-dcb7d0315cf3")
                        },
                        new
                        {
                            Id = new Guid("70f0efe7-b7d8-496f-8bba-d2dace54e52f"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("134a9f90-fcd5-4be8-9fb1-e268ccf9702f"),
                            RoomId = new Guid("036b910f-fb25-441f-a0e9-b089444d90da")
                        },
                        new
                        {
                            Id = new Guid("a20979e0-ef95-4a8c-9475-e6dfe882e257"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("65274cd8-ad94-46ce-ab22-85fccaef03a1"),
                            RoomId = new Guid("036b910f-fb25-441f-a0e9-b089444d90da")
                        },
                        new
                        {
                            Id = new Guid("598784df-a603-4b33-a834-31cc49dead32"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("27780236-fc1b-41e6-afb6-9ea50885658a"),
                            RoomId = new Guid("036b910f-fb25-441f-a0e9-b089444d90da")
                        },
                        new
                        {
                            Id = new Guid("654cf4fc-4fac-4b28-8dc6-b62a30517654"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("c0fa7802-39ec-4fae-bd7a-b0ac42ef0b10"),
                            RoomId = new Guid("036b910f-fb25-441f-a0e9-b089444d90da")
                        },
                        new
                        {
                            Id = new Guid("3bd178b0-f2c7-4c78-be0f-c10f415f0a29"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("3991ec86-1018-460a-8585-b1241983ca39"),
                            RoomId = new Guid("036b910f-fb25-441f-a0e9-b089444d90da")
                        },
                        new
                        {
                            Id = new Guid("56aade82-3a4f-4011-b7ff-75ef7bc51dc6"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("134a9f90-fcd5-4be8-9fb1-e268ccf9702f"),
                            RoomId = new Guid("a0d12b48-bbf0-471a-9ab1-adec22270ca9")
                        },
                        new
                        {
                            Id = new Guid("9a7ea1dd-cca6-465e-80f6-7c441b6e92d5"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("27780236-fc1b-41e6-afb6-9ea50885658a"),
                            RoomId = new Guid("a0d12b48-bbf0-471a-9ab1-adec22270ca9")
                        },
                        new
                        {
                            Id = new Guid("04976b85-e3e1-46b8-a241-57322aae60cb"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("739d492c-6c54-40ee-ab83-c908b6465156"),
                            RoomId = new Guid("8a56daf1-ef94-4ebd-a1d9-da1acc842104")
                        },
                        new
                        {
                            Id = new Guid("84e56e85-01d2-4bcc-877d-21eb1b684586"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("134a9f90-fcd5-4be8-9fb1-e268ccf9702f"),
                            RoomId = new Guid("8a56daf1-ef94-4ebd-a1d9-da1acc842104")
                        },
                        new
                        {
                            Id = new Guid("9c278cdf-f76e-497b-bd64-afca543540a7"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("27780236-fc1b-41e6-afb6-9ea50885658a"),
                            RoomId = new Guid("8a56daf1-ef94-4ebd-a1d9-da1acc842104")
                        },
                        new
                        {
                            Id = new Guid("5ba7602f-773b-47a4-ae7f-481af91f5276"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("65274cd8-ad94-46ce-ab22-85fccaef03a1"),
                            RoomId = new Guid("8a56daf1-ef94-4ebd-a1d9-da1acc842104")
                        },
                        new
                        {
                            Id = new Guid("520c044a-d7cf-4b9a-8e15-495e680b4acd"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("3991ec86-1018-460a-8585-b1241983ca39"),
                            RoomId = new Guid("8a56daf1-ef94-4ebd-a1d9-da1acc842104")
                        },
                        new
                        {
                            Id = new Guid("4fffe4e2-24ee-4d85-bc2d-973daaaa2917"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("27780236-fc1b-41e6-afb6-9ea50885658a"),
                            RoomId = new Guid("6ffbd267-b374-43cf-933c-5ad2a308f7d3")
                        },
                        new
                        {
                            Id = new Guid("97dadc8c-8ab1-4bc2-a6fa-5723f9183370"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("134a9f90-fcd5-4be8-9fb1-e268ccf9702f"),
                            RoomId = new Guid("eb5caa13-2962-41ae-9763-4c6cf4d9abad")
                        },
                        new
                        {
                            Id = new Guid("dac6f581-7c40-45a1-9073-66634037f9f7"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("3991ec86-1018-460a-8585-b1241983ca39"),
                            RoomId = new Guid("eb5caa13-2962-41ae-9763-4c6cf4d9abad")
                        },
                        new
                        {
                            Id = new Guid("15d90812-e051-4a5a-85be-8ab6c18309c1"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("739d492c-6c54-40ee-ab83-c908b6465156"),
                            RoomId = new Guid("1787e7b2-e2ee-4d8f-93cb-e8f8a475fdb4")
                        },
                        new
                        {
                            Id = new Guid("47d2afff-2e6f-4c50-a37a-a9c6835698a5"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("c0fa7802-39ec-4fae-bd7a-b0ac42ef0b10"),
                            RoomId = new Guid("1787e7b2-e2ee-4d8f-93cb-e8f8a475fdb4")
                        },
                        new
                        {
                            Id = new Guid("8e9eee7a-0c98-4d72-83bf-03100443c7ce"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("65274cd8-ad94-46ce-ab22-85fccaef03a1"),
                            RoomId = new Guid("8c6b81b2-e0ad-4247-9d13-225cf5aac8ef")
                        },
                        new
                        {
                            Id = new Guid("95905dab-13d9-4e33-b827-5dd6473f0f24"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("27780236-fc1b-41e6-afb6-9ea50885658a"),
                            RoomId = new Guid("8c6b81b2-e0ad-4247-9d13-225cf5aac8ef")
                        },
                        new
                        {
                            Id = new Guid("44c51341-5b75-43ca-9854-d1a68352fc29"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("739d492c-6c54-40ee-ab83-c908b6465156"),
                            RoomId = new Guid("8c6b81b2-e0ad-4247-9d13-225cf5aac8ef")
                        },
                        new
                        {
                            Id = new Guid("0fbaff65-c8f5-4b19-bb15-4ea27e6c3818"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("134a9f90-fcd5-4be8-9fb1-e268ccf9702f"),
                            RoomId = new Guid("8c6b81b2-e0ad-4247-9d13-225cf5aac8ef")
                        },
                        new
                        {
                            Id = new Guid("04303404-2dfd-43ba-b2f6-6b463ca440ff"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("739d492c-6c54-40ee-ab83-c908b6465156"),
                            RoomId = new Guid("7555549e-1082-422e-9bcf-40ac3b0139c5")
                        },
                        new
                        {
                            Id = new Guid("639ce065-3f62-4f27-a786-fdeb500765fe"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("65274cd8-ad94-46ce-ab22-85fccaef03a1"),
                            RoomId = new Guid("7555549e-1082-422e-9bcf-40ac3b0139c5")
                        },
                        new
                        {
                            Id = new Guid("c4110ff0-3c1b-41f1-99f7-59f48f9653d8"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("40fab3cd-0be5-4aa5-af86-2d1f6c8d50f9"),
                            RoomId = new Guid("7555549e-1082-422e-9bcf-40ac3b0139c5")
                        },
                        new
                        {
                            Id = new Guid("6d2e7a52-bbe3-4944-94ab-7579d7292511"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("c0fa7802-39ec-4fae-bd7a-b0ac42ef0b10"),
                            RoomId = new Guid("7555549e-1082-422e-9bcf-40ac3b0139c5")
                        },
                        new
                        {
                            Id = new Guid("570d8107-60ac-4621-aac3-201f24761a62"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("27780236-fc1b-41e6-afb6-9ea50885658a"),
                            RoomId = new Guid("7555549e-1082-422e-9bcf-40ac3b0139c5")
                        },
                        new
                        {
                            Id = new Guid("3b4b4733-bb21-4eb2-86ea-1a41a26241a9"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("40fab3cd-0be5-4aa5-af86-2d1f6c8d50f9"),
                            RoomId = new Guid("95c91713-9525-441b-9c9e-9a9f2230d7f4")
                        },
                        new
                        {
                            Id = new Guid("3ce1bef7-62b0-4383-aea0-6def888caf19"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("739d492c-6c54-40ee-ab83-c908b6465156"),
                            RoomId = new Guid("95c91713-9525-441b-9c9e-9a9f2230d7f4")
                        },
                        new
                        {
                            Id = new Guid("1a9a2d03-d4cb-40f2-8539-de790a2c8969"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("65274cd8-ad94-46ce-ab22-85fccaef03a1"),
                            RoomId = new Guid("95c91713-9525-441b-9c9e-9a9f2230d7f4")
                        },
                        new
                        {
                            Id = new Guid("9ea23dd4-f03d-4f40-b0ab-70f8b09780f9"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("3991ec86-1018-460a-8585-b1241983ca39"),
                            RoomId = new Guid("95c91713-9525-441b-9c9e-9a9f2230d7f4")
                        },
                        new
                        {
                            Id = new Guid("8b00bbb5-68b7-4e55-8342-de4f14ec1992"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("65274cd8-ad94-46ce-ab22-85fccaef03a1"),
                            RoomId = new Guid("ed001e85-d985-4609-8e7e-f291c15df380")
                        },
                        new
                        {
                            Id = new Guid("100ae5eb-8d8d-4f3b-81a4-78ea22aa5c13"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("739d492c-6c54-40ee-ab83-c908b6465156"),
                            RoomId = new Guid("cf54b286-a6ba-43a6-bfe9-0358ce7c3642")
                        },
                        new
                        {
                            Id = new Guid("a9a2e1d1-1c08-4cf1-b87c-9142f8101fa3"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("40fab3cd-0be5-4aa5-af86-2d1f6c8d50f9"),
                            RoomId = new Guid("cf54b286-a6ba-43a6-bfe9-0358ce7c3642")
                        },
                        new
                        {
                            Id = new Guid("e5ceeaf5-05ff-455a-916b-8a04e413920e"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("27780236-fc1b-41e6-afb6-9ea50885658a"),
                            RoomId = new Guid("cf54b286-a6ba-43a6-bfe9-0358ce7c3642")
                        },
                        new
                        {
                            Id = new Guid("f00d4411-7dea-487c-83b3-c1a5f188f845"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("134a9f90-fcd5-4be8-9fb1-e268ccf9702f"),
                            RoomId = new Guid("cf54b286-a6ba-43a6-bfe9-0358ce7c3642")
                        },
                        new
                        {
                            Id = new Guid("d52090e8-f8cb-44c2-b13d-f92012932ec3"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("65274cd8-ad94-46ce-ab22-85fccaef03a1"),
                            RoomId = new Guid("cf54b286-a6ba-43a6-bfe9-0358ce7c3642")
                        },
                        new
                        {
                            Id = new Guid("ee270522-eaed-4dc7-a56a-79461bf2c610"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("65274cd8-ad94-46ce-ab22-85fccaef03a1"),
                            RoomId = new Guid("8ff91911-6c74-4b4d-8e93-91d4e580d1a1")
                        },
                        new
                        {
                            Id = new Guid("a8907853-5d80-414f-a29f-551b22568d8d"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("40fab3cd-0be5-4aa5-af86-2d1f6c8d50f9"),
                            RoomId = new Guid("8ff91911-6c74-4b4d-8e93-91d4e580d1a1")
                        });
                });

            modelBuilder.Entity("DormitoryManagement.Data.Models.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RoomAssignmentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoomAssignmentId")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("DormitoryManagement.Data.Models.Floor", b =>
                {
                    b.HasOne("DormitoryManagement.Data.Models.Building", "Building")
                        .WithMany("Floors")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("DormitoryManagement.Data.Models.Room", b =>
                {
                    b.HasOne("DormitoryManagement.Data.Models.Floor", "Floor")
                        .WithMany("Rooms")
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Floor");
                });

            modelBuilder.Entity("DormitoryManagement.Data.Models.RoomAssignment", b =>
                {
                    b.HasOne("DormitoryManagement.Data.Models.Room", "Room")
                        .WithMany("RoomAssignments")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("DormitoryManagement.Data.Models.RoomInventory", b =>
                {
                    b.HasOne("DormitoryManagement.Data.Models.InventoryItem", "InventoryItem")
                        .WithMany()
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DormitoryManagement.Data.Models.Room", "Room")
                        .WithMany("RoomInventories")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryItem");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("DormitoryManagement.Data.Models.Student", b =>
                {
                    b.HasOne("DormitoryManagement.Data.Models.RoomAssignment", "RoomAssignment")
                        .WithOne("Student")
                        .HasForeignKey("DormitoryManagement.Data.Models.Student", "RoomAssignmentId");

                    b.Navigation("RoomAssignment");
                });

            modelBuilder.Entity("DormitoryManagement.Data.Models.Building", b =>
                {
                    b.Navigation("Floors");
                });

            modelBuilder.Entity("DormitoryManagement.Data.Models.Floor", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("DormitoryManagement.Data.Models.Room", b =>
                {
                    b.Navigation("RoomAssignments");

                    b.Navigation("RoomInventories");
                });

            modelBuilder.Entity("DormitoryManagement.Data.Models.RoomAssignment", b =>
                {
                    b.Navigation("Student")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
